// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

pub struct UserButton {
pub mut:
	pressed bool
}

pub struct LedGreen {
pub mut:
	on bool
}

pub struct LedYellow {
pub mut:
	on bool
}
