// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

pub struct BenchLoad {
pub mut:
	load u8
}

pub struct BenchTicks {
pub mut:
	wraps u16
	ticks u32
}

pub struct LampCmd {
pub mut:
	level u8
}

pub struct EchoVal {
pub mut:
	level u8
}
