// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct SweepIn {
pub mut:
	// signal "Pot" — ch, transport triple, io -> app
	pot sig.Pot
}
pub struct SweepOut {
pub mut:
	// signal "FanDuty" — ch, transport triple, app -> io
	fan_duty sig.FanDuty
	// signal "LedHi" — ch, transport triple, app -> io
	led_hi sig.LedHi
	// signal "PotLevel" — ch, transport double, app -> can0
	pot_level sig.PotLevel
}
