// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct BenchIn {
pub mut:
	// signal "LampCmd" — ch, transport double, eth0 -> app
	lamp_cmd sig.LampCmd
	// signal "LampCmdSafe" — ch, transport double, eth0 -> app
	lamp_cmd_safe sig.LampCmdSafe
}
pub struct BenchOut {
pub mut:
	// signal "BenchLoad" — ch, transport double, app -> eth0
	bench_load sig.BenchLoad
	// signal "BenchTicks" — ch, transport double, app -> eth0
	bench_ticks sig.BenchTicks
	// signal "EventVal" — ch, transport double, app -> eth0
	event_val sig.EventVal
	// signal "MixedVal" — ch, transport double, app -> eth0
	mixed_val sig.MixedVal
	// signal "EchoVal" — ch, transport double, app -> eth0
	echo_val sig.EchoVal
}
