// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct BenchIn {
pub mut:
}
pub struct BenchOut {
pub mut:
	// signal "BenchLoad" — ch, transport double, app -> eth0
	bench_load sig.BenchLoad
	// signal "BenchTicks" — ch, transport double, app -> eth0
	bench_ticks sig.BenchTicks
}
