// Code generated by tools/dbc2cfg from cantester.dbc — DO NOT EDIT.
// Runtime layer: no heap, operates on fixed [64]u8 frame payloads.
module com

// ===== Powertrain  id=0x100  dlc=8 =====
pub const powertrain_id = u32(0x100)

// EngineSpeed: 0|16 @1 (Intel) unsigned (0.25,0.0) "rpm"
pub fn powertrain_engine_speed_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_engine_speed_phys(data [64]u8) f64 {
	raw := powertrain_engine_speed_raw(data)
	return f64(raw) * 0.25 + 0.0
}

// VehicleSpeed: 16|12 @1 (Intel) unsigned (0.1,0.0) "km/h"
pub fn powertrain_vehicle_speed_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 12 {
		g := 16 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_vehicle_speed_phys(data [64]u8) f64 {
	raw := powertrain_vehicle_speed_raw(data)
	return f64(raw) * 0.1 + 0.0
}

// CoolantTemp: 28|8 @1 (Intel) unsigned (1.0,-40.0) "degC"
pub fn powertrain_coolant_temp_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 28 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_coolant_temp_phys(data [64]u8) f64 {
	raw := powertrain_coolant_temp_raw(data)
	return f64(raw) * 1.0 + -40.0
}

// ThrottlePos: 36|7 @1 (Intel) unsigned (1.0,0.0) "%"
pub fn powertrain_throttle_pos_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 7 {
		g := 36 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_throttle_pos_phys(data [64]u8) f64 {
	raw := powertrain_throttle_pos_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// Gear: 43|4 @1 (Intel) unsigned (1.0,0.0) ""
pub fn powertrain_gear_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 4 {
		g := 43 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_gear_phys(data [64]u8) f64 {
	raw := powertrain_gear_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// CruiseOn: 47|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn powertrain_cruise_on_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 47 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn powertrain_cruise_on_phys(data [64]u8) f64 {
	raw := powertrain_cruise_on_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// ===== Heartbeat  id=0x700  dlc=1 =====
pub const heartbeat_id = u32(0x700)

// Counter: 0|8 @1 (Intel) unsigned (1.0,0.0) ""
pub fn heartbeat_counter_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn heartbeat_counter_phys(data [64]u8) f64 {
	raw := heartbeat_counter_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// ===== Request  id=0x101  dlc=8 =====
pub const request_id = u32(0x101)

// ReqCode: 0|8 @1 (Intel) unsigned (1.0,0.0) ""
pub fn request_req_code_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn request_req_code_phys(data [64]u8) f64 {
	raw := request_req_code_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// ===== Response  id=0x102  dlc=8 =====
pub const response_id = u32(0x102)

// RespCode: 0|8 @1 (Intel) unsigned (1.0,0.0) ""
pub fn response_resp_code_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn response_resp_code_phys(data [64]u8) f64 {
	raw := response_resp_code_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// ===== BodyStatus  id=0x200  dlc=8 =====
pub const body_status_id = u32(0x200)

// DoorFL: 0|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_door_fl_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_door_fl_phys(data [64]u8) f64 {
	raw := body_status_door_fl_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// DoorFR: 1|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_door_fr_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 1 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_door_fr_phys(data [64]u8) f64 {
	raw := body_status_door_fr_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// DoorRL: 2|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_door_rl_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 2 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_door_rl_phys(data [64]u8) f64 {
	raw := body_status_door_rl_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// DoorRR: 3|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_door_rr_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 3 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_door_rr_phys(data [64]u8) f64 {
	raw := body_status_door_rr_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// Locked: 4|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_locked_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 4 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_locked_phys(data [64]u8) f64 {
	raw := body_status_locked_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// Headlights: 5|2 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_headlights_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 2 {
		g := 5 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_headlights_phys(data [64]u8) f64 {
	raw := body_status_headlights_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// Indicators: 7|2 @1 (Intel) unsigned (1.0,0.0) ""
pub fn body_status_indicators_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 2 {
		g := 7 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_indicators_phys(data [64]u8) f64 {
	raw := body_status_indicators_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// InteriorTemp: 16|8 @1 (Intel) unsigned (0.5,-40.0) "degC"
pub fn body_status_interior_temp_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 16 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn body_status_interior_temp_phys(data [64]u8) f64 {
	raw := body_status_interior_temp_raw(data)
	return f64(raw) * 0.5 + -40.0
}

// ===== WheelSpeeds  id=0x300  dlc=8 =====
pub const wheel_speeds_id = u32(0x300)

// WheelFL: 0|16 @1 (Intel) unsigned (0.01,0.0) "km/h"
pub fn wheel_speeds_wheel_fl_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn wheel_speeds_wheel_fl_phys(data [64]u8) f64 {
	raw := wheel_speeds_wheel_fl_raw(data)
	return f64(raw) * 0.01 + 0.0
}

// WheelFR: 16|16 @1 (Intel) unsigned (0.01,0.0) "km/h"
pub fn wheel_speeds_wheel_fr_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 16 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn wheel_speeds_wheel_fr_phys(data [64]u8) f64 {
	raw := wheel_speeds_wheel_fr_raw(data)
	return f64(raw) * 0.01 + 0.0
}

// WheelRL: 32|16 @1 (Intel) unsigned (0.01,0.0) "km/h"
pub fn wheel_speeds_wheel_rl_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 32 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn wheel_speeds_wheel_rl_phys(data [64]u8) f64 {
	raw := wheel_speeds_wheel_rl_raw(data)
	return f64(raw) * 0.01 + 0.0
}

// WheelRR: 48|16 @1 (Intel) unsigned (0.01,0.0) "km/h"
pub fn wheel_speeds_wheel_rr_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 48 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn wheel_speeds_wheel_rr_phys(data [64]u8) f64 {
	raw := wheel_speeds_wheel_rr_raw(data)
	return f64(raw) * 0.01 + 0.0
}

// ===== BrakeStatus  id=0x301  dlc=4 =====
pub const brake_status_id = u32(0x301)

// BrakePressure: 0|16 @1 (Intel) unsigned (0.1,0.0) "kPa"
pub fn brake_status_brake_pressure_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn brake_status_brake_pressure_phys(data [64]u8) f64 {
	raw := brake_status_brake_pressure_raw(data)
	return f64(raw) * 0.1 + 0.0
}

// ABSActive: 16|1 @1 (Intel) unsigned (1.0,0.0) ""
pub fn brake_status_absactive_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 1 {
		g := 16 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn brake_status_absactive_phys(data [64]u8) f64 {
	raw := brake_status_absactive_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// BrakePedal: 17|7 @1 (Intel) unsigned (1.0,0.0) "%"
pub fn brake_status_brake_pedal_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 7 {
		g := 17 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn brake_status_brake_pedal_phys(data [64]u8) f64 {
	raw := brake_status_brake_pedal_raw(data)
	return f64(raw) * 1.0 + 0.0
}

// ===== BatteryStatus  id=0x400  dlc=8 =====
pub const battery_status_id = u32(0x400)

// PackVoltage: 0|16 @1 (Intel) unsigned (0.01,0.0) "V"
pub fn battery_status_pack_voltage_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 0 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn battery_status_pack_voltage_phys(data [64]u8) f64 {
	raw := battery_status_pack_voltage_raw(data)
	return f64(raw) * 0.01 + 0.0
}

// PackCurrent: 16|16 @1 (Intel) signed (0.1,0.0) "A"
pub fn battery_status_pack_current_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 16 {
		g := 16 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn battery_status_pack_current_phys(data [64]u8) f64 {
	raw := battery_status_pack_current_raw(data)
	mut v := f64(raw)
	if raw & (u64(1) << 15) != 0 {
		v = f64(i64(raw) - (i64(1) << 16))
	}
	return v * 0.1 + 0.0
}

// SoC: 32|8 @1 (Intel) unsigned (0.5,0.0) "%"
pub fn battery_status_so_c_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 32 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn battery_status_so_c_phys(data [64]u8) f64 {
	raw := battery_status_so_c_raw(data)
	return f64(raw) * 0.5 + 0.0
}

// PackTemp: 40|8 @1 (Intel) unsigned (1.0,-40.0) "degC"
pub fn battery_status_pack_temp_raw(data [64]u8) u64 {
	mut raw := u64(0)
	for i in 0 .. 8 {
		g := 40 + i
		byte_idx := g / 8
		if byte_idx >= 64 {
			continue
		}
		bit := (data[byte_idx] >> (g % 8)) & 1
		raw |= u64(bit) << i
	}
	return raw
}
pub fn battery_status_pack_temp_phys(data [64]u8) f64 {
	raw := battery_status_pack_temp_raw(data)
	return f64(raw) * 1.0 + -40.0
}
