// cfg2v — BUILD-TIME tool (heap is fine here). Reads config/ecu.toml and emits
// gen/ecu_gen.v: static, no-alloc config tables (channel ids, per-channel
// transport, partition table) consumed by the runtime. Nothing parses TOML on
// the target. Companion to tools/dbc2cfg (which generates the signal codec).
//
//   v run tools/cfg2v/gen.v config/ecu.toml gen/ecu_gen.v
module main

import os
import toml

fn main() {
	args := os.args
	if args.len < 3 {
		eprintln('usage: cfg2v <ecu.toml> <out.v>')
		exit(2)
	}
	doc := toml.parse_file(args[1]) or { panic('parse ${args[1]}: ${err}') }

	mut b := []string{}
	b << '// Code generated by tools/cfg2v from ${os.file_name(args[1])} — DO NOT EDIT.'
	b << '// Static, no-alloc ECU config tables consumed by the runtime.'
	b << 'module gen'
	b << ''
	b << 'pub enum Transport {'
	b << '\tseqlock // 1x'
	b << '\tdouble  // 2x'
	b << '\ttriple  // 3x'
	b << '}'

	// --- IOC channels: cross-partition signals only (from != to). Local signals
	//     (from == to) route through a partition cell and get no channel. ---
	sigs := doc.value('signal').array()
	mut transports := []string{}
	mut chcount := 0
	b << ''
	b << '// IOC channels — const = slot id (cross-partition signals, declaration order)'
	for s in sigs {
		m := s.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		from := (m['from'] or { toml.Any('') }).string()
		to := (m['to'] or { toml.Any('') }).string()
		if from == to {
			continue // local signal — no IOC channel
		}
		mut tr := (m['transport'] or { toml.Any('double') }).string()
		if from == 'io' || to == 'io' {
			tr = 'triple' // derived for io endpoints (docs/io.md), never configured — the runtime table must match loom2v's glue
		}
		b << 'pub const ${snake(name)}_ch = ${chcount}'
		transports << transport_variant(tr)
		chcount++
	}
	// --- Route crossings: a SIGNAL route whose buses sit on different cores carries its decoded
	//     physical value (one f64) over an IOC channel between the two comm owners
	//     (REQ-TOPO-010). Allocated here — cfg2v is the single channel allocator — in route
	//     declaration order; loom2v emits the publish/acquire ends against these consts.
	mut bus_cores := map[string]int{}
	if bt := doc.value_opt('bus') {
		for bname, bcfg in bt.as_map() {
			bus_cores[bname] = int((bcfg.as_map()['core'] or { toml.Any(0) }).int())
		}
	}
	for rt in doc.value('route').array() {
		m := rt.as_map()
		sig := (m['signal'] or { toml.Any('') }).string()
		if sig == '' {
			continue // frame routes never cross cores (loom2v rejects) — no channel
		}
		fm := (m['from'] or { toml.Any(map[string]toml.Any{}) }).as_map()
		tm := (m['to'] or { toml.Any(map[string]toml.Any{}) }).as_map()
		fb := (fm['bus'] or { toml.Any('') }).string()
		tb := (tm['bus'] or { toml.Any('') }).string()
		if (bus_cores[fb] or { 0 }) == (bus_cores[tb] or { 0 }) {
			continue // same core: the route stays intra-thread, no channel
		}
		tf := (tm['frame'] or { toml.Any('') }).string()
		b << 'pub const xr_${snake(tb)}_${snake(tf)}_${snake(sig)}_ch = ${chcount}'
		// triple, not double: an rx burst (source cadence < the 10 ms bridge tick) laps the
		// consumer, and the double buffer tears exactly then; the triple buffer's exchange
		// hands over whole-buffer ownership, tear-free at any rate (codex #200).
		transports << transport_variant('triple')
		chcount++
	}
	// The host pools are fixed (osal_native.c: 256 slots per variant). Past that, publishes
	// are silently range-rejected — a large config would build green and lose signals at
	// runtime. Fail generation instead (codex #200).
	if chcount > 256 {
		panic('cfg2v: ${chcount} IOC channels exceed the host pool (256 slots, osal_native.c) — split the config or grow the pool deliberately')
	}
	b << 'pub const ioc_channel_count = ${chcount}'
	b << ''
	// Per-channel transport (index = channel id). With no cross-partition IOC channels there is
	// nothing to index — and neither an empty fixed literal ([]!) compiles nor a growable []T is
	// allowed in -gc none runtime code — so omit the const entirely (ioc_channel_count = 0 already
	// says there are none, and nothing reads the table when it's empty).
	if transports.len == 0 {
		b << '// (no cross-partition IOC channels — no transport table)'
	} else {
		b << '// Per-channel transport (index = channel id)'
		b << 'pub const ioc_transport = [${transports.join(', ')}]!'
	}

	// --- Partitions (declaration order = partition id) ---
	parts := doc.value('partition').array()
	mut cores := []string{}
	mut trusted := []string{}
	for p in parts {
		m := p.as_map()
		cores << (m['core'] or { toml.Any(0) }).int().str()
		trusted << (m['trusted'] or { toml.Any(false) }).bool().str()
	}
	b << ''
	b << '// Partitions — index = partition id'
	b << 'pub const partition_count = ${parts.len}'
	b << 'pub const partition_cores = [${cores.join(', ')}]!'
	b << 'pub const partition_trusted = [${trusted.join(', ')}]!'

	// --- Network Management (per network; ms -> us) ---
	// value_opt (not value): a config WITHOUT an [nm.*] section must generate
	// nothing. value() returns Null for a missing key, which as_map() coerces into
	// a bogus single-entry map (net "0") -> a phantom nm_0_* block.
	if nm_any := doc.value_opt('nm') {
		nm := nm_any.as_map()
		if nm.len > 0 {
			b << ''
			b << '// Network Management (per network)'
			for net, cfg in nm {
				// only real module [nm.<net>] SUB-TABLES are ours; the scalar-key [nm] form
				// (node/enabled/alive/… from the multi-node dissolution) is loom2v's. A scalar
				// value is not a map, so skip it (as_map() would wrap it into a 1-elem map).
				if cfg !is map[string]toml.Any {
					continue
				}
				m := cfg.as_map()
				tx_id := (m['tx_id'] or { toml.Any(0) }).int()
				// rx_lo/rx_hi are REQUIRED: they bound the NM id range. Defaulting
				// them to tx_id would make the node deaf — the binding excludes its
				// own tx_id, so a [tx_id, tx_id] range matches nothing.
				rx_lo := m['rx_lo'] or {
					eprintln('cfg2v: [nm.${net}] is missing rx_lo (the NM id range low bound)')
					exit(1)
				}
				rx_hi := m['rx_hi'] or {
					eprintln('cfg2v: [nm.${net}] is missing rx_hi (the NM id range high bound)')
					exit(1)
				}
				b << 'pub const nm_${net}_node_id = u8(${(m['node_id'] or { toml.Any(0) }).int()})'
				b << 'pub const nm_${net}_tx_id = u32(0x${tx_id.hex()})'
				b << 'pub const nm_${net}_rx_lo = u32(0x${rx_lo.int().hex()})'
				b << 'pub const nm_${net}_rx_hi = u32(0x${rx_hi.int().hex()})'
				// partial networks this node statically requests (48-bit bitmask,
				// 0 = none). .u64() (not .int()) so masks using bits 32..47 survive.
				b << 'pub const nm_${net}_pn_local = u64(${(m['pn_local'] or { toml.Any(0) }).u64()})'
				b << 'pub const nm_${net}_msg_cycle_us = u64(${int((m['msg_cycle_ms'] or { toml.Any(0) }).int()) * 1000})'
				b << 'pub const nm_${net}_timeout_us = u64(${int((m['timeout_ms'] or { toml.Any(0) }).int()) * 1000})'
				b << 'pub const nm_${net}_repeat_us = u64(${int((m['repeat_ms'] or { toml.Any(0) }).int()) * 1000})'
				b << 'pub const nm_${net}_wait_sleep_us = u64(${int((m['wait_sleep_ms'] or { toml.Any(0) }).int()) * 1000})'
			}
		}
	}

	// --- Bus config (per bus: CAN-FD flag) ---
	// value_opt (same reason as [nm] above): a bus-less config (io-only node) must
	// generate nothing — Null.as_map() would coerce into a phantom "0" bus.
	if busv := doc.value_opt('bus') {
		bus := busv.as_map()
		if bus.len > 0 {
			b << ''
			b << '// Bus config (per bus)'
			for name, cfg in bus {
				m := cfg.as_map()
				b << 'pub const ${snake(name)}_fd = ${(m['fd'] or { toml.Any(false) }).bool()}'
				// NOTE: the bus *interface* name (e.g. "vcan0") is a platform binding and
				// lives in the hand-written main.v (the no-heap exempt entry), not here —
				// gen/ is no-`string` runtime config.
			}
		}
	}

	os.write_file(args[2], b.join('\n') + '\n') or { panic('write ${args[2]}: ${err}') }
	eprintln('cfg2v: ${chcount} IOC channels, ${parts.len} partitions -> ${args[2]}')
}

// transport_variant maps a config string to a Transport enum literal. The HW
// transports (hw_sem/dma/mailbox) are target backends; on host they fall back to
// the closest software scheme.
fn transport_variant(s string) string {
	return match s {
		'seqlock' { 'Transport.seqlock' }
		'triple' { 'Transport.triple' }
		'dma' { 'Transport.double' } // DMA fills a double buffer
		else { 'Transport.double' } // double / hw_sem / mailbox -> double on host
	}
}

// snake converts CamelCase / mixed names to snake_case identifiers.
fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			if (prev >= `a` && prev <= `z`) || (prev >= `0` && prev <= `9`) {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}
