// cfg2v — BUILD-TIME tool (heap is fine here). Reads config/ecu.toml and emits
// gen/ecu_gen.v: static, no-alloc config tables (channel ids, per-channel
// transport, partition table) consumed by the runtime. Nothing parses TOML on
// the target. Companion to tools/dbc2cfg (which generates the signal codec).
//
//   v run tools/cfg2v/gen.v config/ecu.toml gen/ecu_gen.v
module main

import os
import toml

fn main() {
	args := os.args
	if args.len < 3 {
		eprintln('usage: cfg2v <ecu.toml> <out.v>')
		exit(2)
	}
	doc := toml.parse_file(args[1]) or { panic('parse ${args[1]}: ${err}') }

	mut b := []string{}
	b << '// Code generated by tools/cfg2v from ${os.file_name(args[1])} — DO NOT EDIT.'
	b << '// Static, no-alloc ECU config tables consumed by the runtime.'
	b << 'module gen'
	b << ''
	b << 'pub enum Transport {'
	b << '\tseqlock // 1x'
	b << '\tdouble  // 2x'
	b << '\ttriple  // 3x'
	b << '}'

	// --- IOC channels (declaration order = slot id) ---
	ioc := doc.value('ioc').array()
	if ioc.len == 0 {
		panic('ecu.toml: no [[ioc]] channels')
	}
	mut transports := []string{}
	b << ''
	b << '// IOC channels — const = slot id (declaration order)'
	for i, ch in ioc {
		m := ch.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		tr := (m['transport'] or { toml.Any('double') }).string()
		b << 'pub const ${snake(name)}_ch = ${i}'
		transports << transport_variant(tr)
	}
	b << 'pub const ioc_channel_count = ${ioc.len}'
	b << ''
	b << '// Per-channel transport (index = channel id)'
	b << 'pub const ioc_transport = [${transports.join(', ')}]!'

	// --- Partitions (declaration order = partition id) ---
	parts := doc.value('partition').array()
	mut cores := []string{}
	mut trusted := []string{}
	for p in parts {
		m := p.as_map()
		cores << (m['core'] or { toml.Any(0) }).int().str()
		trusted << (m['trusted'] or { toml.Any(false) }).bool().str()
	}
	b << ''
	b << '// Partitions — index = partition id'
	b << 'pub const partition_count = ${parts.len}'
	b << 'pub const partition_cores = [${cores.join(', ')}]!'
	b << 'pub const partition_trusted = [${trusted.join(', ')}]!'

	// --- Network Management timings (per network; ms -> us) ---
	nm := doc.value('nm').as_map()
	if nm.len > 0 {
		b << ''
		b << '// Network Management timings (per network)'
		for net, cfg in nm {
			m := cfg.as_map()
			b << 'pub const nm_${net}_node_id = u8(${(m['node_id'] or { toml.Any(0) }).int()})'
			b << 'pub const nm_${net}_tx_id = u32(0x${(m['tx_id'] or { toml.Any(0) }).int().hex()})'
			b << 'pub const nm_${net}_msg_cycle_us = u64(${int((m['msg_cycle_ms'] or { toml.Any(0) }).int()) * 1000})'
			b << 'pub const nm_${net}_timeout_us = u64(${int((m['timeout_ms'] or { toml.Any(0) }).int()) * 1000})'
			b << 'pub const nm_${net}_repeat_us = u64(${int((m['repeat_ms'] or { toml.Any(0) }).int()) * 1000})'
			b << 'pub const nm_${net}_wait_sleep_us = u64(${int((m['wait_sleep_ms'] or { toml.Any(0) }).int()) * 1000})'
		}
	}

	os.write_file(args[2], b.join('\n') + '\n') or { panic('write ${args[2]}: ${err}') }
	eprintln('cfg2v: ${ioc.len} IOC channels, ${parts.len} partitions -> ${args[2]}')
}

// transport_variant maps a config string to a Transport enum literal. The HW
// transports (hw_sem/dma/mailbox) are target backends; on host they fall back to
// the closest software scheme.
fn transport_variant(s string) string {
	return match s {
		'seqlock' { 'Transport.seqlock' }
		'triple' { 'Transport.triple' }
		'dma' { 'Transport.double' } // DMA fills a double buffer
		else { 'Transport.double' } // double / hw_sem / mailbox -> double on host
	}
}

// snake converts CamelCase / mixed names to snake_case identifiers.
fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			if (prev >= `a` && prev <= `z`) || (prev >= `0` && prev <= `9`) {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}
