// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
// Per-FB input/output port structs (signal provenance in comments).
module main

pub struct SpeedFilterIn {
pub mut:
	// signal "VehicleSpeed" — ch, transport double, io -> sense
	vehicle_speed VehicleSpeed
}
pub struct SpeedFilterOut {
pub mut:
	// signal "FilteredSpeed" — local cell in partition "sense"
	filtered_speed FilteredSpeed
}

pub struct OverspeedDetectorIn {
pub mut:
	// signal "FilteredSpeed" — local cell in partition "sense"
	filtered_speed FilteredSpeed
}
pub struct OverspeedDetectorOut {
pub mut:
	// signal "Overspeed" — ch, transport double, sense -> ctrl
	overspeed Overspeed
}

pub struct EngineMonitorIn {
pub mut:
	// signal "EngineSpeed" — ch, transport double, io -> ctrl
	engine_speed EngineSpeed
}
pub struct EngineMonitorOut {
pub mut:
	// signal "HighRev" — local cell in partition "ctrl"
	high_rev HighRev
}

pub struct LampControllerIn {
pub mut:
	// signal "Overspeed" — ch, transport double, sense -> ctrl
	overspeed Overspeed
	// signal "HighRev" — local cell in partition "ctrl"
	high_rev HighRev
}
pub struct LampControllerOut {
pub mut:
	// signal "WarnLamp" — ch, transport double, ctrl -> io
	warn_lamp WarnLamp
}
