// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

pub struct Pot {
pub mut:
	count u16
}

pub struct FanDuty {
pub mut:
	duty u16
}

pub struct LedHi {
pub mut:
	on bool
}

pub struct PotLevel {
pub mut:
	level u32
}
