// sigmap — BUILD-TIME tool (`make trace`). Cross-references config/ecu.toml with
// the DBC (via candb) to generate docs/signal-map.md: every signal's end-to-end
// provenance (DBC signal, frame, bit layout, scaling, path, producers/consumers).
// This is the "follow a signal" index from docs/application-model.md.
//
//   v -path "@vlib|@vmodules|tools" run tools/sigmap/gen.v config/ecu.toml docs/signal-map.md
module main

import os
import toml
import tools.candb

struct DbcRef {
	msg    string
	id     u32
	start  int
	length int
	factor f64
	offset f64
	unit   string
	found  bool
}

fn main() {
	args := os.args
	if args.len < 3 {
		eprintln('usage: sigmap <ecu.toml> <out.md>')
		exit(2)
	}
	doc := toml.parse_file(args[1]) or { panic('parse ${args[1]}: ${err}') }

	// declared buses — an endpoint that names one is EXTERNAL (on the wire).
	mut buses := map[string]bool{}
	for bname, _ in doc.value('bus').as_map() {
		buses[bname] = true
	}

	// DBC signal lookup (by name) from the [import] dbc, if any.
	mut dbc_of := map[string]DbcRef{}
	dbc_path := (doc.value('import').as_map()['dbc'] or { toml.Any('') }).string()
	if dbc_path != '' && os.exists(dbc_path) {
		db := candb.load_dbc_file(dbc_path) or { candb.Database{} }
		for m in db.messages {
			for s in m.signals {
				dbc_of[s.name] = DbcRef{
					msg: m.name, id: m.id, start: s.start_bit, length: s.length
					factor: s.factor, offset: s.offset, unit: s.unit, found: true
				}
			}
		}
	}

	// FB producers (writes) / consumers (reads) per signal, from [[fb]].
	mut producers := map[string][]string{}
	mut consumers := map[string][]string{}
	for fb in doc.value('fb').array() {
		fm := fb.as_map()
		name := (fm['name'] or { toml.Any('') }).string()
		for h in (fm['handler'] or { toml.Any([]toml.Any{}) }).array() {
			hm := h.as_map()
			for r in (hm['reads'] or { toml.Any([]toml.Any{}) }).array() {
				consumers[r.string()] << name
			}
			for w in (hm['writes'] or { toml.Any([]toml.Any{}) }).array() {
				producers[w.string()] << name
			}
		}
	}

	mut b := []string{}
	b << '# Signal map (generated)'
	b << ''
	b << 'Generated by `make trace` (tools/sigmap) from `config/ecu.toml` + the DBC.'
	b << 'DO NOT EDIT — follow a signal here, or via the provenance comments in `sig/ports_gen.v`.'
	b << ''
	b << '| Signal | Unit | Source | DBC signal | Frame | Layout | Scaling | Path | Producers | Consumers |'
	b << '|--------|------|--------|------------|-------|--------|---------|------|-----------|-----------|'

	// value_opt so a config with no [[signal]] blocks yields an empty table (not one phantom
	// row) — doc.value('signal') on a missing key returns a single empty element.
	signals := if s := doc.value_opt('signal') { s.array() } else { []toml.Any{} }
	for ch in signals {
		m := ch.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		from := (m['from'] or { toml.Any('') }).string()
		to := (m['to'] or { toml.Any('') }).string()
		mut tr := (m['transport'] or { toml.Any('double') }).string()
		if from == 'io' || to == 'io' {
			tr = 'triple' // derived for io endpoints (docs/io.md), never configured
		}
		from_bus := from in buses
		to_bus := to in buses
		external := from_bus || to_bus
		local := from == to && !external
		d := dbc_of[name] or { DbcRef{} }

		// external = a bus endpoint (the explicit model); show that bus as source.
		source := if external {
			if from_bus { from } else { to }
		} else {
			from
		}
		dbc_sig := if d.found { '${d.msg}.${name}' } else { '—' }
		frame := if d.found { '0x${d.id.hex()}' } else { '—' }
		layout := if d.found { '${d.start}|${d.length}' } else { '—' }
		scaling := if d.found && d.factor != 1.0 { 'x${d.factor}' } else { '—' }
		unit := if d.unit != '' { d.unit } else { '—' }
		path := if local { '${from} (local cell)' } else { '${from}→IOC(${tr})→${to}' }
		prod := join_or(producers[name] or { []string{} }, '(${from})')
		cons := join_or(consumers[name] or { []string{} }, '(${to})')
		b << '| ${name} | ${unit} | ${source} | ${dbc_sig} | ${frame} | ${layout} | ${scaling} | ${path} | ${prod} | ${cons} |'
	}

	os.write_file(args[2], b.join('\n') + '\n') or { panic('write ${args[2]}: ${err}') }
	eprintln('sigmap: ${doc.value('signal').array().len} signals -> ${args[2]}')
}

fn join_or(items []string, fallback string) string {
	if items.len == 0 {
		return fallback
	}
	return items.join(', ')
}
