// sysgen — the SYSTEM generator (multi-node P1b, docs/multi-node.md). The
// "dissolution": a cross-node signal is authored ONCE in system.toml (name,
// fields, producer, bus, DBC frame); each node authors only its INTERNALS
// (partitions/threads/FBs with reads/writes by signal name). sysgen merges them
// into a COMPLETE ecu.toml per node — the derived [bus]/[[signal]]/[[frame]] bus
// wiring + the generated [nm] identity, prepended to the authored internals —
// which then feeds the existing ecucheck/loom2v unchanged.
//
//   v run tools/sysgen examples/system_bench/system.toml
//
// Generated files land in <node-dir>/gen-ecu.toml. The generator NEVER edits the
// authored node or the DBC (the DBC is the hand-authored wire contract).
module main

import os
import toml
import sysmodel

fn main() {
	if os.args.len < 2 {
		eprintln('usage: sysgen <system.toml>')
		exit(2)
	}
	path := os.args[1]
	mut sys := sysmodel.parse_system(path) or {
		eprintln('sysgen: ${err}')
		exit(2)
	}
	// validate BEFORE generating — never emit wiring for an inconsistent system
	// (the same cross-node checks syscheck runs; a bad system is not buildable).
	load_errs := sys.load_nodes_partial()
	mut had_err := false
	for e in load_errs {
		eprintln('sysgen: ${e}')
		had_err = true
	}
	issues := sysmodel.validate_system_gen(sys)
	for iss in issues {
		if iss.severity == .error {
			eprintln('sysgen: ERROR [${iss.req}] ${iss.msg}')
			had_err = true
		}
	}
	if had_err {
		eprintln('sysgen: refusing to generate an inconsistent system')
		exit(1)
	}

	for n in sys.nodes {
		out := generate_node(sys, n) or {
			eprintln('sysgen: node "${n.name}": ${err}')
			exit(1)
		}
		// generated files live beside system.toml, so [import] dbc resolves the
		// same as the bus's dbc path (relative to the system dir).
		gen_path := os.join_path(sys.dir, 'gen-${n.name}.toml')
		os.write_file(gen_path, out) or {
			eprintln('sysgen: write ${gen_path}: ${err}')
			exit(1)
		}
		// gate the GENERATED node (partials never pass alone — the guarantee is
		// that what sysgen EMITS is buildable). ecucheck is the SCHEMA gate;
		// loom2v is the TARGET gate — it enforces the comm-thread bridge
		// constraints ecucheck can't see (a threadx external signal must be a
		// trivial u32 LE @ bit0, a standard id, cyclic, no E2E/SecOC), so a clean
		// verdict means the node actually generates, not just parses.
		gerrs := sysmodel.ecucheck_errors(gen_path)
		if gerrs.len > 0 {
			for e in gerrs {
				eprintln('sysgen: generated ${n.name}: ${e}')
			}
			exit(1)
		}
		bus := node_bus(sys, n) or {
			eprintln('sysgen: node "${n.name}": ${err}')
			exit(1)
		}
		dbc_path := if os.is_abs_path(bus.dbc) { bus.dbc } else { os.join_path(sys.dir, bus.dbc) }
		lerrs := sysmodel.loom2v_errors(gen_path, dbc_path)
		if lerrs.len > 0 {
			for e in lerrs {
				eprintln('sysgen: generated ${n.name}: loom2v: ${e}')
			}
			exit(1)
		}
		println('sysgen: ${n.name} -> ${gen_path} (ok)')
	}
	println('sysgen: ${sys.nodes.len} node(s) generated + gated')
}

// generate_node emits the complete ecu.toml text for one node: the derived
// system-facing preamble + the node's authored internals verbatim (last, so its
// [[fb.handler]] nested tables never precede another section — the V TOML
// nested-parse trap, vlang/v#27684).
fn generate_node(sys sysmodel.System, node sysmodel.Node) !string {
	node_path := if os.is_abs_path(node.ecu) { node.ecu } else { os.join_path(sys.dir, node.ecu) }
	authored := os.read_file(node_path) or { return error('read ${node_path}: ${err}') }
	doc := toml.parse_file(node_path) or { return error('parse ${node_path}: ${err}') }
	view := sysmodel.parse_node_view(doc)

	// which local partition owns each signal (the FB that reads/writes it lives
	// in a thread that lives in a partition) — the [[signal]] from/to endpoint.
	sig_part := signal_partitions(doc)

	// the node sits on one bus in P1 — the bus carrying its signals.
	bus := node_bus(sys, node) or { return err }

	mut b := []string{}
	b << '# GENERATED by tools/sysgen from system.toml — DO NOT EDIT.'
	b << '# Node "${node.name}": authored internals + system-owned wiring/identity.'
	b << ''
	if bus.dbc != '' {
		b << '[import]'
		b << 'dbc = "${bus.dbc}"'
		b << ''
	}
	b << '[bus.${bus.interface}]'
	b << 'interface = "${bus.interface}"'
	b << 'fd        = ${bus.fd}'
	b << 'core      = 0'
	b << ''
	// identity, allocated by system.toml (REQ-TOPO-005): node id from [[node]],
	// alive = the cluster's peers base + node, peers + timing from [bus.*.nm].
	b << '[nm]'
	b << 'node  = 0x${node.nm.hex()}'
	if bus.has_nm_cluster {
		b << 'alive = 0x${(bus.nm_peers_lo + node.nm).hex()}'
		b << 'peers = [0x${bus.nm_peers_lo.hex()}, 0x${bus.nm_peers_hi.hex()}]'
		if bus.nm_msg_cycle_ms > 0 {
			b << 'msg_cycle_ms = ${bus.nm_msg_cycle_ms}'
		}
		if bus.nm_timeout_ms > 0 {
			b << 'timeout_ms = ${bus.nm_timeout_ms}'
		}
		if bus.nm_repeat_ms > 0 {
			b << 'repeat_ms = ${bus.nm_repeat_ms}'
		}
		if bus.nm_wait_sleep_ms > 0 {
			b << 'wait_sleep_ms = ${bus.nm_wait_sleep_ms}'
		}
	}
	b << ''

	// produced signals (this node is the SysSignal.producer): tx on the bus.
	mut emitted_frames := map[string]bool{}
	for sig in sys.signals {
		if sig.producer != node.name {
			continue
		}
		part := sig_part[sig.name] or { return error('signal "${sig.name}" is produced here but no FB writes it') }
		b << '[[signal]]'
		b << 'name   = "${sig.name}"'
		b << 'fields = ${fields_inline(sig.fields)}'
		b << 'from   = "${part}"'
		b << 'to     = "${bus.interface}"'
		b << ''
		// one [[frame]] per PDU: several signals may share a DBC message, but its
		// tx cadence is configured once (validated to agree in check_signals_dissolved).
		if sig.frame != '' && sig.frame !in emitted_frames {
			emitted_frames[sig.frame] = true
			cyc := sysmodel.effective_cycle_ms(sig.cycle_ms)
			b << '  [[frame]]'
			b << '  name = "${sig.frame}"'
			b << '  bus  = "${bus.interface}"'
			b << '  tx   = { mode = "cyclic", cycle_ms = ${cyc} } # trailing comment terminates the nested [[frame]] parse (vlang/v#27684)'
			b << ''
		}
	}
	// consumed signals (an FB here reads a signal ANOTHER node produces): rx.
	// dedup repeated reads — two handlers reading one signal is a single rx port.
	mut rx_seen := map[string]bool{}
	for name in view.fb_reads {
		if name in rx_seen {
			continue
		}
		rx_seen[name] = true
		sig := sys.signal_by_name(name) or { continue }
		if sig.producer == node.name {
			continue // locally produced (or self-loop) — not a bus rx
		}
		part := sig_part[name] or { continue }
		b << '[[signal]]'
		b << 'name   = "${sig.name}"'
		b << 'fields = ${fields_inline(sig.fields)}'
		b << 'from   = "${bus.interface}"'
		b << 'to     = "${part}"'
		b << ''
	}

	// the authored internals, verbatim and LAST.
	b << '# --- authored internals (${os.file_name(node_path)}) ---'
	b << authored.trim_space()
	b << ''
	return b.join('\n')
}

// signal_partitions maps each signal a node's FBs read/write to the partition
// that owns the handling FB (fb -> thread -> partition).
fn signal_partitions(doc toml.Doc) map[string]string {
	// thread name -> partition name
	mut thread_part := map[string]string{}
	for p in (doc.value_opt('partition') or { toml.Any([]toml.Any{}) }).array() {
		pm := p.as_map()
		pname := (pm['name'] or { toml.Any('') }).string()
		for t in (pm['thread'] or { toml.Any([]toml.Any{}) }).array() {
			tname := (t.as_map()['name'] or { toml.Any('') }).string()
			if tname != '' {
				thread_part[tname] = pname
			}
		}
	}
	mut out := map[string]string{}
	for fb in (doc.value_opt('fb') or { toml.Any([]toml.Any{}) }).array() {
		fm := fb.as_map()
		thr := (fm['thread'] or { toml.Any('') }).string()
		part := thread_part[thr] or { '' }
		if part == '' {
			continue
		}
		for h in (fm['handler'] or { toml.Any([]toml.Any{}) }).array() {
			hm := h.as_map()
			for r in (hm['reads'] or { toml.Any([]toml.Any{}) }).array() {
				out[r.string()] = part
			}
			for w in (hm['writes'] or { toml.Any([]toml.Any{}) }).array() {
				out[w.string()] = part
			}
		}
	}
	return out
}

// fields_inline renders a { name = "type", … } TOML inline table deterministically
// (sorted keys, so regeneration is byte-stable).
fn fields_inline(fields map[string]string) string {
	mut keys := fields.keys()
	keys.sort()
	mut parts := []string{}
	for k in keys {
		parts << '${k} = "${fields[k]}"'
	}
	return '{ ${parts.join(", ")} }'
}

// node_bus returns the single system bus a P1 node sits on (its signals ride it).
fn node_bus(sys sysmodel.System, node sysmodel.Node) !sysmodel.Bus {
	if node.buses.len == 0 {
		return error('node is on no bus')
	}
	return sys.bus_by_name(node.buses[0]) or { error('bus "${node.buses[0]}" not declared') }
}

