// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

// RxStatus: what the bridge last learned about a received signal (docs/diagnostics.md
// §3.2). The ZERO value is never_received, so a signal nothing has published yet — and a
// freestanding image, where no initialiser runs — reads as not-yet-received, never healthy.
pub enum RxStatus as u8 {
	never_received // no good frame yet
	ok // the value came from a good frame
	timeout // the reception deadline passed (silence is the newest fact)
	integrity // the newest frame failed its E2E CRC or its SecOC check
}

pub struct BenchLoad {
pub mut:
	load u8
}

pub struct BenchTicks {
pub mut:
	wraps u16
	ticks u32
}

pub struct EventVal {
pub mut:
	level u8
}

pub struct MixedVal {
pub mut:
	setpoint u16
}

pub struct LampCmd {
pub mut:
	level u8
}

pub struct LampCmdSafe {
pub mut:
	level u8
	status RxStatus
}

pub struct EchoVal {
pub mut:
	level u8
}
