// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct MeterIn {
pub mut:
	// signal "PotVolt" — ch, transport triple, io -> app
	pot_volt sig.PotVolt
}
pub struct MeterOut {
pub mut:
	// signal "LedHi" — ch, transport triple, app -> io
	led_hi sig.LedHi
}
