// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

pub struct VehicleSpeed {
pub mut:
	kph u16
	valid bool
}

pub struct EngineSpeed {
pub mut:
	rpm u16
	valid bool
}

pub struct FilteredSpeed {
pub mut:
	kph u16
	valid bool
}

pub struct Overspeed {
pub mut:
	active bool
}

pub struct HighRev {
pub mut:
	active bool
}

pub struct WarnLamp {
pub mut:
	on bool
}

pub struct SecureStatus {
pub mut:
	level u8
}
