// dbc2cfg — BUILD-TIME tool (heap is fine here). Reads a DBC via candb and
// generates comm/com/dbc_gen.v: no-alloc signal accessors over [64]u8 that
// transcribe candb's raw_value/physical algorithm with the bit layout baked in.
// candb itself never ships to the target.
//
//   v -path "@vlib|@vmodules|tools" run tools/dbc2cfg/gen.v <dbc> <out.v>
module main

import os
import strings
import tools.candb

fn main() {
	args := os.args
	if args.len < 3 {
		eprintln('usage: dbc2cfg <dbc_path> <out.v>')
		exit(2)
	}
	db := candb.load_dbc_file(args[1]) or { panic('load dbc: ${err}') }

	mut b := strings.new_builder(4096)
	b.write_string('// Code generated by tools/dbc2cfg from ${os.file_name(args[1])} — DO NOT EDIT.\n')
	b.write_string('// Runtime layer: no heap, operates on fixed [64]u8 frame payloads.\n')
	b.write_string('module gen\n')

	mut nsig := 0
	for m in db.messages {
		base_msg := snake(m.name)
		b.write_string('\n// ===== ${m.name}  id=0x${m.id.hex()}  dlc=${m.dlc} =====\n')
		b.write_string('pub const ${base_msg}_id = u32(0x${m.id.hex()})\n')
		b.write_string('pub const ${base_msg}_dlc = u8(${m.dlc})\n')
		for s in m.signals {
			base := '${base_msg}_${snake(s.name)}'
			be := if s.byte_order == .big_endian { '@0 (Motorola)' } else { '@1 (Intel)' }
			sign := if s.is_signed { 'signed' } else { 'unsigned' }
			b.write_string('\n// ${s.name}: ${s.start_bit}|${s.length} ${be} ${sign} (${s.factor},${s.offset}) "${s.unit}"\n')
			emit_raw(mut b, base, s)
			emit_phys(mut b, base, s)
			emit_set_raw(mut b, base, s)
			emit_set(mut b, base, s)
			nsig++
		}
	}

	os.write_file(args[2], b.str()) or { panic('write: ${err}') }
	eprintln('dbc2cfg: ${db.messages.len} messages, ${nsig} signals -> ${args[2]}')
}

fn emit_raw(mut b strings.Builder, base string, s candb.Signal) {
	b.write_string('pub fn ${base}_raw(data [64]u8) u64 {\n')
	b.write_string('\tmut raw := u64(0)\n')
	if s.byte_order == .big_endian {
		b.write_string('\tmut pos := ${s.start_bit}\n')
		b.write_string('\tfor _ in 0 .. ${s.length} {\n')
		b.write_string('\t\tbyte_idx := pos / 8\n')
		b.write_string('\t\tbit_idx := pos % 8\n')
		b.write_string('\t\traw <<= 1\n')
		b.write_string('\t\tif byte_idx < 64 {\n')
		b.write_string('\t\t\traw |= u64((data[byte_idx] >> bit_idx) & 1)\n')
		b.write_string('\t\t}\n')
		b.write_string('\t\tpos = if bit_idx == 0 { pos + 15 } else { pos - 1 }\n')
		b.write_string('\t}\n')
	} else {
		b.write_string('\tfor i in 0 .. ${s.length} {\n')
		b.write_string('\t\tg := ${s.start_bit} + i\n')
		b.write_string('\t\tbyte_idx := g / 8\n')
		b.write_string('\t\tif byte_idx >= 64 {\n\t\t\tcontinue\n\t\t}\n')
		b.write_string('\t\tbit := (data[byte_idx] >> (g % 8)) & 1\n')
		b.write_string('\t\traw |= u64(bit) << i\n')
		b.write_string('\t}\n')
	}
	b.write_string('\treturn raw\n}\n')
}

fn emit_phys(mut b strings.Builder, base string, s candb.Signal) {
	b.write_string('pub fn ${base}_phys(data [64]u8) f64 {\n')
	b.write_string('\traw := ${base}_raw(data)\n')
	if s.is_signed && s.length > 0 && s.length < 64 {
		b.write_string('\tmut v := f64(raw)\n')
		b.write_string('\tif raw & (u64(1) << ${s.length - 1}) != 0 {\n')
		b.write_string('\t\tv = f64(i64(raw) - i64(u64(1) << ${s.length}))\n')
		b.write_string('\t}\n')
		b.write_string('\treturn v * ${f64lit(s.factor)} + ${f64lit(s.offset)}\n')
	} else {
		b.write_string('\treturn f64(raw) * ${f64lit(s.factor)} + ${f64lit(s.offset)}\n')
	}
	b.write_string('}\n')
}

// emit_set_raw is the inverse of emit_raw: write `raw` into the frame at the
// signal's bit position (Intel little-endian / Motorola big-endian sawtooth).
fn emit_set_raw(mut b strings.Builder, base string, s candb.Signal) {
	b.write_string('pub fn ${base}_set_raw(mut data [64]u8, raw u64) {\n')
	if s.byte_order == .big_endian {
		b.write_string('\tmut pos := ${s.start_bit}\n')
		b.write_string('\tfor i in 0 .. ${s.length} {\n')
		b.write_string('\t\tbyte_idx := pos / 8\n')
		b.write_string('\t\tbit_idx := pos % 8\n')
		b.write_string('\t\tbit := u8((raw >> (${s.length} - 1 - i)) & 1)\n')
		b.write_string('\t\tif byte_idx < 64 {\n')
		b.write_string('\t\t\tmask := u8(1) << bit_idx\n')
		b.write_string('\t\t\tdata[byte_idx] = (data[byte_idx] & ~mask) | (bit << bit_idx)\n')
		b.write_string('\t\t}\n')
		b.write_string('\t\tpos = if bit_idx == 0 { pos + 15 } else { pos - 1 }\n')
		b.write_string('\t}\n')
	} else {
		b.write_string('\tfor i in 0 .. ${s.length} {\n')
		b.write_string('\t\tg := ${s.start_bit} + i\n')
		b.write_string('\t\tbyte_idx := g / 8\n')
		b.write_string('\t\tif byte_idx >= 64 {\n\t\t\tcontinue\n\t\t}\n')
		b.write_string('\t\tbit_idx := g % 8\n')
		b.write_string('\t\tmask := u8(1) << bit_idx\n')
		b.write_string('\t\tbit := u8((raw >> i) & 1)\n')
		b.write_string('\t\tdata[byte_idx] = (data[byte_idx] & ~mask) | (bit << bit_idx)\n')
		b.write_string('\t}\n')
	}
	b.write_string('}\n')
}

// emit_set converts a physical value to raw and writes it (inverse of emit_phys).
// Rounds half away from zero (a bare +0.5 truncates negatives wrongly).
fn emit_set(mut b strings.Builder, base string, s candb.Signal) {
	mask := if s.length >= 64 { '~u64(0)' } else { '((u64(1) << ${s.length}) - 1)' }
	b.write_string('pub fn ${base}_set(mut data [64]u8, phys f64) {\n')
	b.write_string('\tx := (phys - ${f64lit(s.offset)}) / ${f64lit(s.factor)}\n')
	b.write_string('\tmut raw := i64(if x >= 0.0 { x + 0.5 } else { x - 0.5 })\n')
	if s.length > 0 && s.length < 64 {
		b.write_string('\tif raw < 0 {\n\t\traw += i64(u64(1) << ${s.length})\n\t}\n')
	}
	b.write_string('\t${base}_set_raw(mut data, u64(raw) & ${mask})\n')
	b.write_string('}\n')
}

// snake converts CamelCase / mixed names to snake_case identifiers.
fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			prev_lower := prev >= `a` && prev <= `z`
			prev_digit := prev >= `0` && prev <= `9`
			if prev_lower || prev_digit {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32 // to lowercase
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}

// f64lit renders an f64 as a valid V float literal (always with a decimal point).
fn f64lit(x f64) string {
	s := x.str()
	if s.contains('.') || s.contains('e') || s.contains('E') {
		return s
	}
	return s + '.0'
}
