// loom2v — BUILD-TIME tool. From [[fb]] in ecu.toml it generates two files:
//   * sig/ports_gen.v  — per-FB `In`/`Out` port structs (with signal provenance)
//   * gen/loom_gen.v    — the Loom wiring: state, snapshot glue, scheduled entry
//
// Convention: a port/signal name P maps to the value type `sig.P` and the IOC
// channel `gen.<snake(P)>_ch`. Each handler's glue snapshots its input signals
// into an `In`, calls the FB method, and publishes its `Out` — using each
// channel's configured transport.
//
//   v run tools/loom2v/gen.v config/ecu.toml sig/ports_gen.v gen/loom_gen.v
module main

import os
import toml

struct SigInfo {
	idx       int
	transport string
	from      string
	to        string
}

fn main() {
	args := os.args
	if args.len < 4 {
		eprintln('usage: loom2v <ecu.toml> <ports_out.v> <glue_out.v>')
		exit(2)
	}
	doc := toml.parse_file(args[1]) or { panic('parse ${args[1]}: ${err}') }

	// signal -> channel info (declaration order, transport, direction)
	mut sig_of := map[string]SigInfo{}
	for i, ch in doc.value('ioc').array() {
		m := ch.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		sig_of[name] = SigInfo{
			idx:       i
			transport: (m['transport'] or { toml.Any('double') }).string()
			from:      (m['from'] or { toml.Any('') }).string()
			to:        (m['to'] or { toml.Any('') }).string()
		}
	}
	// partition -> core
	mut core_of := map[string]int{}
	for p in doc.value('partition').array() {
		m := p.as_map()
		core_of[(m['name'] or { toml.Any('') }).string()] = int((m['core'] or { toml.Any(0) }).int())
	}
	// group FBs by partition
	mut by_part := map[string][]toml.Any{}
	for c in doc.value('fb').array() {
		by_part[(c.as_map()['partition'] or { toml.Any('') }).string()] << c
	}

	mut ports := []string{}
	ports << '// Code generated by tools/loom2v from ${os.file_name(args[1])} — DO NOT EDIT.'
	ports << '// Per-FB input/output port structs (signal provenance in comments).'
	ports << 'module sig'

	mut glue := []string{}
	glue << '// Code generated by tools/loom2v from ${os.file_name(args[1])} — DO NOT EDIT.'
	glue << '// Loom wiring per partition: state, snapshot glue, scheduled entry.'
	glue << 'module gen'
	glue << ''
	glue << 'import app'
	glue << 'import sig'
	glue << 'import loom'
	glue << 'import osal'

	for part, clist in by_part {
		glue << ''
		glue << 'struct Partition_${part}_state {'
		glue << 'mut:'
		for c in clist {
			cname := (c.as_map()['name'] or { toml.Any('') }).string()
			glue << '\t${snake(cname)} app.${cname}'
		}
		glue << '}'

		mut regs := []string{}
		for c in clist {
			cm := c.as_map()
			cname := (cm['name'] or { toml.Any('') }).string()
			field := snake(cname)
			for h in (cm['handler'] or { toml.Any([]toml.Any{}) }).array() {
				hm := h.as_map()
				hname := (hm['name'] or { toml.Any('') }).string()
				period_us := int((hm['period_ms'] or { toml.Any(0) }).int()) * 1000
				reads := (hm['reads'] or { toml.Any([]toml.Any{}) }).array()
				writes := (hm['writes'] or { toml.Any([]toml.Any{}) }).array()

				// --- port structs (module sig) ---
				ports << ''
				ports << 'pub struct ${cname}In {'
				ports << 'pub mut:'
				for r in reads {
					ports << provenance(r.string(), sig_of)
					ports << '\t${snake(r.string())} ${r.string()}'
				}
				ports << '}'
				ports << 'pub struct ${cname}Out {'
				ports << 'pub mut:'
				for w in writes {
					ports << provenance(w.string(), sig_of)
					ports << '\t${snake(w.string())} ${w.string()}'
				}
				ports << '}'

				// --- glue handler (module gen) ---
				gname := 'handler_${part}_${field}_${hname}'
				glue << ''
				glue << 'fn ${gname}(ctx voidptr) {'
				glue << '\tmut st := unsafe { &Partition_${part}_state(ctx) }'
				glue << '\tmut inp := sig.${cname}In{}'
				for r in reads {
					rn := r.string()
					tr := sig_of[rn] or { SigInfo{} }
					glue << '\tosal.${acquire_fn(tr.transport)}(${snake(rn)}_ch, &inp.${snake(rn)}, u8(sizeof(inp.${snake(rn)})))'
				}
				glue << '\tmut outp := sig.${cname}Out{}'
				glue << '\tst.${field}.${hname}(inp, mut outp)'
				for w in writes {
					wn := w.string()
					tr := sig_of[wn] or { SigInfo{} }
					glue << '\tosal.${publish_fn(tr.transport)}(${snake(wn)}_ch, &outp.${snake(wn)}, u8(sizeof(outp.${snake(wn)})))'
				}
				glue << '}'
				regs << '\tsched.every(${period_us}, ${gname}, &st)'
			}
		}

		glue << ''
		glue << 'pub fn partition_${part}(core int, arg voidptr) {'
		glue << '\tosal.pin_to_core(${core_of[part] or { 0 }})'
		glue << '\tmut st := Partition_${part}_state{}'
		glue << '\tmut sched := loom.Scheduler{}'
		for r in regs {
			glue << r
		}
		glue << '\tfor {'
		glue << '\t\tsched.run(osal.now_us())'
		glue << '\t\tosal.sleep_us(1000)'
		glue << '\t}'
		glue << '}'
	}

	os.write_file(args[2], ports.join('\n') + '\n') or { panic('write ${args[2]}: ${err}') }
	os.write_file(args[3], glue.join('\n') + '\n') or { panic('write ${args[3]}: ${err}') }
	eprintln('loom2v: ${by_part.len} partition(s) -> ${args[2]}, ${args[3]}')
}

fn provenance(name string, sig_of map[string]SigInfo) string {
	s := sig_of[name] or { return '\t// signal "${name}"' }
	return '\t// signal "${name}" — ch ${s.idx}, transport ${s.transport}, ${s.from} -> ${s.to}'
}

fn acquire_fn(tr string) string {
	return match tr {
		'seqlock' { 'ioc_read' }
		'triple' { 'ioc_acquire' }
		else { 'ioc_acquire2' }
	}
}

fn publish_fn(tr string) string {
	return match tr {
		'seqlock' { 'ioc_write' }
		'triple' { 'ioc_publish' }
		else { 'ioc_publish2' }
	}
}

fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			if (prev >= `a` && prev <= `z`) || (prev >= `0` && prev <= `9`) {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}
