// loom2v — BUILD-TIME tool. From ecu.toml (+ the DBC) it generates, for one
// example:
//   * sig/signals_gen.v   — `module sig`:   signal value types (from .fields)
//   * ports/ports_gen.v   — `module ports`: per-FB In/Out structs (imports sig)
//   * gen/loom_gen.v      — `module gen`:   state + snapshot glue + entries,
//                                           the generated COM bus bridge, run()
//
// An endpoint is a PARTITION or a BUS. That makes external vs internal explicit:
//   * endpoint is a bus  -> EXTERNAL: COM-encoded via the DBC; the bus bridge
//                           decodes rx signals -> IOC, encodes tx signals <- IOC
//   * both partitions    -> INTERNAL: from == to -> local cell, else IOC channel
//
//   v run tools/loom2v/gen.v <ecu.toml> <bus.dbc> <signals_out> <ports_out> <glue_out>
// (run from a freestanding example with its own v.mod, so module names are short)
module main

import os
import toml
import tools.candb

struct SigInfo {
mut:
	transport string
	from      string
	to        string
	local     bool
	external  bool   // an endpoint is a bus
	bus       string // the bus name (if external)
	rx        bool   // external && bus is the `from` endpoint (bus -> app)
	val_field string // the signal's value field (the non-"valid" field)
	val_type  string // its V type
	has_valid bool   // a `valid` field is present
	dbc_msg   string // snake(DBC message name) carrying this signal (if external)
}

// IsotpConn is one [[isotp]] diagnostic connection on a bus.
struct IsotpConn {
	name  string
	bus   string
	rx_id int
	tx_id int
	bs    int
	stmin int
}

// DidCfg is one [[did]]: constant bytes, a writable RAM cell, and/or a live signal.
struct DidCfg {
	id       int
	bytes    []u8
	writable bool
	signal   string
}

// Route is one [[route]]: forward a raw frame from one bus to another (gateway),
// without decoding it to signals. to_id == 0 means keep the source id.
struct Route {
mut:
	from_bus   string
	from_frame string
	from_id    int
	to_bus     string
	to_id      int
}

fn main() {
	args := os.args
	if args.len < 6 {
		eprintln('usage: loom2v <ecu.toml> <bus.dbc> <signals_out> <ports_out> <glue_out>')
		exit(2)
	}
	ecu := args[1]
	dbc := args[2]
	doc := toml.parse_file(ecu) or { panic('parse ${ecu}: ${err}') }

	// declared buses (endpoint names that mean "external / on the wire")
	mut buses := map[string]bool{}
	mut bus_core := map[string]int{}
	for bname, bcfg in doc.value('bus').as_map() {
		buses[bname] = true
		bus_core[bname] = int((bcfg.as_map()['core'] or { toml.Any(0) }).int())
	}

	// signal value types -> module sig (generated from each [[signal]] `fields`)
	mut signals := []string{}
	signals << '// Code generated by tools/loom2v from ${os.file_name(ecu)} — DO NOT EDIT.'
	signals << 'module sig'

	mut sig_of := map[string]SigInfo{}
	mut sig_names := []string{}
	mut has_external := false
	for s in doc.value('signal').array() {
		m := s.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		from := (m['from'] or { toml.Any('') }).string()
		to := (m['to'] or { toml.Any('') }).string()

		from_bus := from in buses
		to_bus := to in buses
		external := from_bus || to_bus
		if external {
			has_external = true
		}

		fields := (m['fields'] or { toml.Any(map[string]toml.Any{}) }).as_map()
		if fields.len == 0 {
			panic('ecu.toml: signal "${name}" needs `fields` (e.g. fields = { kph = "u16" })')
		}
		// value field = the single non-"valid" field; `valid` (if any) is freshness
		mut val_field := ''
		mut val_type := ''
		mut has_valid := false
		signals << ''
		signals << 'pub struct ${name} {'
		signals << 'pub mut:'
		for fname, ftype in fields {
			signals << '\t${fname} ${ftype.string()}'
			if fname == 'valid' {
				has_valid = true
			} else if val_field == '' {
				val_field = fname
				val_type = ftype.string()
			}
		}
		signals << '}'

		sig_of[name] = SigInfo{
			transport: (m['transport'] or { toml.Any('double') }).string()
			from:      from
			to:        to
			local:     from == to
			external:  external
			bus:       if from_bus { from } else { to }
			rx:        from_bus
			val_field: val_field
			val_type:  val_type
			has_valid: has_valid
		}
		sig_names << name
	}

	// Map each external signal to its DBC message (so the bridge can name the
	// generated codec fns / id / dlc). External signals must be in the DBC.
	if has_external {
		db := candb.load_dbc_file(dbc) or { panic('external signals need a DBC: load ${dbc}: ${err}') }
		for sname in sig_names {
			mut si := sig_of[sname] or { continue }
			if !si.external {
				continue
			}
			si.dbc_msg = dbc_message_of(db, sname) or {
				panic('signal "${sname}" has a bus endpoint but is not in ${os.file_name(dbc)}')
			}
			sig_of[sname] = si
		}
	}

	// Per-PDU COM behaviour ([[frame]]), keyed by snake(DBC message name):
	// tx mode/timing, rx deadline. Absent -> defaults (tx cyclic@100ms, no rx t/o).
	mut tx_mode := map[string]string{}
	mut tx_cycle_us := map[string]int{}
	mut tx_min_us := map[string]int{}
	mut rx_timeout_us := map[string]int{}
	mut e2e_on := map[string]bool{} // frame has end-to-end protection
	mut e2e_id := map[string]int{}
	mut e2e_crc := map[string]int{}
	mut e2e_ctr := map[string]int{}
	mut secoc_on := map[string]bool{} // frame has SecOC authentication
	mut secoc_id := map[string]int{}
	mut secoc_fresh := map[string]int{}
	mut secoc_mac := map[string]int{}
	mut secoc_maclen := map[string]int{}
	mut secoc_key := map[string][]u8{}
	for f in doc.value('frame').array() {
		fm := f.as_map()
		fk := snake((fm['name'] or { toml.Any('') }).string())
		if 'tx' in fm {
			txm := (fm['tx'] or { toml.Any('') }).as_map()
			tx_mode[fk] = (txm['mode'] or { toml.Any('cyclic') }).string()
			tx_cycle_us[fk] = int((txm['cycle_ms'] or { toml.Any(0) }).int()) * 1000
			tx_min_us[fk] = int((txm['min_delay_ms'] or { toml.Any(0) }).int()) * 1000
		}
		if 'rx' in fm {
			rxm := (fm['rx'] or { toml.Any('') }).as_map()
			rx_timeout_us[fk] = int((rxm['timeout_ms'] or { toml.Any(0) }).int()) * 1000
		}
		if 'e2e' in fm {
			em := (fm['e2e'] or { toml.Any('') }).as_map()
			e2e_on[fk] = true
			e2e_id[fk] = int((em['data_id'] or { toml.Any(0) }).int())
			e2e_crc[fk] = int((em['crc_pos'] or { toml.Any(0) }).int())
			e2e_ctr[fk] = int((em['counter_pos'] or { toml.Any(0) }).int())
		}
		if 'secoc' in fm {
			sm := (fm['secoc'] or { toml.Any('') }).as_map()
			secoc_on[fk] = true
			secoc_id[fk] = int((sm['data_id'] or { toml.Any(0) }).int())
			secoc_fresh[fk] = int((sm['fresh_pos'] or { toml.Any(0) }).int())
			secoc_mac[fk] = int((sm['mac_pos'] or { toml.Any(0) }).int())
			secoc_maclen[fk] = int((sm['mac_len'] or { toml.Any(4) }).int())
			secoc_key[fk] = parse_hex((sm['key'] or { toml.Any('') }).string())
		}
	}
	has_e2e := e2e_on.len > 0
	has_secoc := secoc_on.len > 0

	// Raw-PDU gateway routes ([[route]]): forward a frame bus->bus, no decode.
	mut routes := []Route{}
	for r in doc.value('route').array() {
		m := r.as_map()
		fm := (m['from'] or { toml.Any('') }).as_map()
		tm := (m['to'] or { toml.Any('') }).as_map()
		fb := (fm['bus'] or { toml.Any('') }).string()
		if fb == '' {
			continue
		}
		routes << Route{
			from_bus:   fb
			from_frame: (fm['frame'] or { toml.Any('') }).string()
			to_bus:     (tm['bus'] or { toml.Any('') }).string()
			to_id:      int((tm['id'] or { toml.Any(0) }).int())
		}
	}
	has_routes := routes.len > 0
	if has_routes {
		db := candb.load_dbc_file(dbc) or { panic('routes need a DBC: load ${dbc}: ${err}') }
		for i, r in routes {
			id := dbc_id_of(db, snake(r.from_frame)) or {
				panic('route: frame "${r.from_frame}" is not a message in ${os.file_name(dbc)}')
			}
			routes[i].from_id = id
			if routes[i].to_id == 0 {
				routes[i].to_id = id // keep the source id unless remapped
			}
		}
	}

	// Validate E2E byte positions against each frame's DLC (they index unsafe into
	// the frame's [64]u8 in the generated bridge).
	if has_e2e || has_secoc {
		db := candb.load_dbc_file(dbc) or { panic('protected frames need a DBC: load ${dbc}: ${err}') }
		for fk, _ in e2e_on {
			dlc := dbc_dlc_of(db, fk) or {
				panic('e2e: frame "${fk}" is not a message in ${os.file_name(dbc)}')
			}
			cp := e2e_crc[fk] or { 0 }
			np := e2e_ctr[fk] or { 0 }
			if cp < 0 || cp >= dlc || np < 0 || np >= dlc || cp == np {
				panic('e2e ${fk}: crc_pos=${cp}, counter_pos=${np} must be distinct and within dlc=${dlc}')
			}
		}
		for fk, _ in secoc_on {
			dlc := dbc_dlc_of(db, fk) or {
				panic('secoc: frame "${fk}" is not a message in ${os.file_name(dbc)}')
			}
			fp := secoc_fresh[fk] or { 0 }
			mp := secoc_mac[fk] or { 0 }
			ml := secoc_maclen[fk] or { 0 }
			if (secoc_key[fk] or { []u8{} }).len != 16 {
				panic('secoc ${fk}: key must be 16 bytes (AES-128)')
			}
			if ml < 1 || ml > 16 || fp < 0 || fp >= dlc || mp < 0 || mp + ml > dlc
				|| (fp >= mp && fp < mp + ml) {
				panic('secoc ${fk}: fresh_pos=${fp}, mac_pos=${mp}, mac_len=${ml} must be 1..16, fit within dlc=${dlc}, and not overlap')
			}
		}
	}

	// ISO-TP diagnostic connections ([[isotp]]).
	mut isotp_conns := []IsotpConn{}
	for c in doc.value('isotp').array() {
		m := c.as_map()
		name := (m['name'] or { toml.Any('') }).string()
		if name == '' {
			continue // absent [[isotp]] section can yield a phantom empty entry
		}
		isotp_conns << IsotpConn{
			name:  name
			bus:   (m['bus'] or { toml.Any('') }).string()
			rx_id: int((m['rx_id'] or { toml.Any(0) }).int())
			tx_id: int((m['tx_id'] or { toml.Any(0) }).int())
			bs:    int((m['bs'] or { toml.Any(0) }).int())
			stmin: int((m['stmin_ms'] or { toml.Any(0) }).int())
		}
	}

	// UDS Data Identifiers ([[did]]): constant (ascii/bytes), writable RAM, or live signal.
	mut dids := []DidCfg{}
	for d in doc.value('did').array() {
		m := d.as_map()
		id := int((m['id'] or { toml.Any(0) }).int())
		if id == 0 {
			continue
		}
		mut bytes := []u8{}
		if 'ascii' in m {
			for ch in (m['ascii'] or { toml.Any('') }).string() {
				bytes << u8(ch)
			}
		} else if 'bytes' in m {
			bytes = parse_hex((m['bytes'] or { toml.Any('') }).string())
		}
		dids << DidCfg{
			id:       id
			bytes:    bytes
			writable: (m['writable'] or { toml.Any(false) }).bool()
			signal:   (m['signal'] or { toml.Any('') }).string()
		}
	}

	mut core_of := map[string]int{}
	for p in doc.value('partition').array() {
		m := p.as_map()
		core_of[(m['name'] or { toml.Any('') }).string()] = int((m['core'] or { toml.Any(0) }).int())
	}
	mut by_part := map[string][]toml.Any{}
	for c in doc.value('fb').array() {
		by_part[(c.as_map()['partition'] or { toml.Any('') }).string()] << c
	}

	// --- telemetry: give every app partition + every bus(bridge) a scratch slot,
	//     remembering its core, so a generated tx can sum processor load by core
	//     and ship it as a CpuLoad CAN frame. Gated by an [telemetry] config block. ---
	mut telem_on := false
	mut telem_bus := ''
	mut telem_id := u32(0)
	mut telem_detail_id := u32(0) // optional LoadDetail frame (multi-window + overruns)
	mut telem_period_us := u64(1_000_000)
	mut telem_iface := ''
	mut telem_slot := map[string]int{}
	mut slot_core := []int{}
	if tcfg := doc.value_opt('telemetry') {
		tm := tcfg.as_map()
		telem_on = (tm['enabled'] or { toml.Any(false) }).bool()
		telem_bus = (tm['bus'] or { toml.Any('') }).string()
		telem_id = u32((tm['id'] or { toml.Any(0) }).int())
		telem_detail_id = u32((tm['detail_id'] or { toml.Any(0) }).int())
		if pms := tm['period_ms'] {
			telem_period_us = u64(pms.int()) * 1000
		}
	}

	// [target] baremetal: emit a single-core inline superloop instead of the host's
	// spawned partitions + osal. No threads, no osal (POSIX now_us/sleep_us don't
	// exist bare-metal); the timebase is board_now_us() and the loop paces to a fixed
	// tick. Requires all signals partition-local (no COM bus bridge).
	mut target_on := false
	mut target_tick_us := u64(1000)
	if tgt := doc.value_opt('target') {
		tm := tgt.as_map()
		target_on = (tm['kind'] or { toml.Any('') }).string() == 'baremetal'
		if tms := tm['tick_ms'] {
			target_tick_us = u64(tms.int()) * 1000
		}
	}
	if target_on && has_external {
		panic('loom2v: [target] baremetal does not support external/bus signals yet ' +
			'(every [[signal]] must be partition-local: from == to)')
	}

	if telem_on {
		if bc := doc.value('bus').as_map()[telem_bus] {
			telem_iface = (bc.as_map()['interface'] or { toml.Any('') }).string()
		}
		mut tparts := by_part.keys()
		tparts.sort()
		for tp in tparts {
			if slot_core.len < 16 { // scratch holds 16 u64s
				telem_slot['p:${tp}'] = slot_core.len
				slot_core << (core_of[tp] or { 0 })
			}
		}
		mut tbuses := bus_core.keys()
		tbuses.sort()
		for tb in tbuses {
			if slot_core.len < 16 {
				telem_slot['b:${tb}'] = slot_core.len
				slot_core << (bus_core[tb] or { 0 })
			}
		}
	}

	mut ports := []string{}
	ports << '// Code generated by tools/loom2v from ${os.file_name(ecu)} — DO NOT EDIT.'
	ports << 'module ports'
	ports << ''
	ports << 'import sig'

	// glue references sig.* only for local-cell types; import it only if needed.
	mut has_local := false
	for part, _ in by_part {
		for sname in sig_names {
			si := sig_of[sname] or { continue }
			if si.local && si.from == part {
				has_local = true
			}
		}
	}

	mut glue := []string{}
	glue << '// Code generated by tools/loom2v from ${os.file_name(ecu)} — DO NOT EDIT.'
	glue << 'module gen'
	glue << ''
	if has_local || has_external {
		glue << 'import sig' // local-cell types and/or bus-bridge signal structs
	}
	glue << 'import ports'
	glue << 'import app'
	glue << 'import loom'
	if !target_on {
		glue << 'import osal' // host: IOC + now_us/sleep_us. Target has none of these.
	}
	if telem_on {
		glue << 'import comm.telem' // CpuLoad packing for the load-telemetry tx
	}
	if has_external || isotp_conns.len > 0 || telem_on {
		glue << 'import driver.can' // the generated bus bridge
	}
	if has_external {
		glue << 'import comm.com' // per-PDU TX modes + RX deadline monitoring
	}
	if has_e2e {
		glue << 'import comm.e2e' // end-to-end protection (CRC + alive counter)
	}
	if has_secoc {
		glue << 'import comm.secoc' // SecOC authentication (AES-CMAC + freshness)
	}
	if isotp_conns.len > 0 {
		glue << 'import comm.isotp' // ISO-TP diagnostic transport
		glue << 'import comm.uds' // UDS diagnostic services
	}

	mut all_regs := map[string][]string{} // per-partition sched.every(...) lines, reused by target run()
	for part, clist in by_part {
		glue << ''
		glue << 'struct Partition_${part}_state {'
		glue << 'mut:'
		for c in clist {
			cname := (c.as_map()['name'] or { toml.Any('') }).string()
			glue << '\t${snake(cname)} app.${cname}'
		}
		for sname in sig_names {
			si := sig_of[sname] or { continue }
			if si.local && si.from == part {
				glue << '\tcell_${snake(sname)} sig.${sname} // local FB->FB signal'
			}
		}
		glue << '}'

		mut regs := []string{}
		for c in clist {
			cm := c.as_map()
			cname := (cm['name'] or { toml.Any('') }).string()
			field := snake(cname)
			for h in (cm['handler'] or { toml.Any([]toml.Any{}) }).array() {
				hm := h.as_map()
				hname := (hm['name'] or { toml.Any('') }).string()
				period_us := int((hm['period_ms'] or { toml.Any(0) }).int()) * 1000
				reads := (hm['reads'] or { toml.Any([]toml.Any{}) }).array()
				writes := (hm['writes'] or { toml.Any([]toml.Any{}) }).array()

				// --- port structs (module ports) ---
				ports << ''
				ports << 'pub struct ${cname}In {'
				ports << 'pub mut:'
				for r in reads {
					ports << provenance(r.string(), sig_of)
					ports << '\t${snake(r.string())} sig.${r.string()}'
				}
				ports << '}'
				ports << 'pub struct ${cname}Out {'
				ports << 'pub mut:'
				for w in writes {
					ports << provenance(w.string(), sig_of)
					ports << '\t${snake(w.string())} sig.${w.string()}'
				}
				ports << '}'

				// --- glue handler (module gen) ---
				gname := 'handler_${part}_${field}_${hname}'
				glue << ''
				glue << 'fn ${gname}(ctx voidptr) {'
				glue << '\tmut st := unsafe { &Partition_${part}_state(ctx) }'
				glue << '\tmut inp := ports.${cname}In{}'
				for r in reads {
					rn := r.string()
					si := sig_of[rn] or { SigInfo{} }
					if si.local {
						glue << '\tinp.${snake(rn)} = st.cell_${snake(rn)} // local'
					} else {
						glue << '\tosal.${acquire_fn(si.transport)}(${snake(rn)}_ch, &inp.${snake(rn)}, u8(sizeof(inp.${snake(rn)})))'
					}
				}
				glue << '\tmut outp := ports.${cname}Out{}'
				glue << '\tst.${field}.${hname}(inp, mut outp)'
				for w in writes {
					wn := w.string()
					si := sig_of[wn] or { SigInfo{} }
					if si.local {
						glue << '\tst.cell_${snake(wn)} = outp.${snake(wn)} // local'
					} else {
						glue << '\tosal.${publish_fn(si.transport)}(${snake(wn)}_ch, &outp.${snake(wn)}, u8(sizeof(outp.${snake(wn)})))'
					}
				}
				glue << '}'
				regs << '\tsched.every(${period_us}, ${gname}, &st)'
			}
		}
		all_regs[part] = regs.clone()

		// Host: one spawned superloop per partition, paced by osal.sleep_us. Target
		// mode emits a single inline superloop in run() instead (see below).
		if !target_on {
			glue << ''
			glue << 'pub fn partition_${part}(core int, arg voidptr) {'
			glue << '\tosal.pin_to_core(${core_of[part] or { 0 }})'
			glue << '\tmut st := Partition_${part}_state{}'
			glue << '\tmut sched := loom.Scheduler{}'
			for r in regs {
				glue << r
			}
			glue << '\tfor {'
			glue << '\t\tloom_t0 := osal.now_us()'
			glue << '\t\tsched.run(loom_t0)'
			glue << '\t\tloom_t1 := osal.now_us()'
			glue << '\t\tsched.account(loom_t1 - loom_t0, loom_t1) // per-core load'
			if telem_on && 'p:${part}' in telem_slot {
				glue << '\t\tosal.scratch_set(${telem_slot['p:${part}']}, u64(sched.load_permille()))'
			}
			glue << '\t\tosal.sleep_us(1000)'
			glue << '\t}'
			glue << '}'
		}
	}

	// --- generated COM bus bridge(s): decode rx -> IOC, IOC -> encode tx ---
	mut bus_names := []string{}
	mut bus_dests := map[string][]string{} // bus -> its gateway destination buses
	for bname, _ in buses {
		bb := snake(bname)
		mut rx_by_msg := map[string][]string{}
		mut tx_by_msg := map[string][]string{}
		for sname in sig_names {
			si := sig_of[sname] or { continue }
			if !si.external || si.bus != bname {
				continue
			}
			if si.rx {
				rx_by_msg[si.dbc_msg] << sname
			} else {
				tx_by_msg[si.dbc_msg] << sname
			}
		}
		mut conns := []IsotpConn{}
		for c in isotp_conns {
			if c.bus == bname {
				conns << c
			}
		}
		// routes that ORIGINATE on this bus, and the distinct destination buses
		mut my_routes := []Route{}
		mut dests := []string{}
		for r in routes {
			if r.from_bus == bname {
				my_routes << r
				if r.to_bus !in dests {
					dests << r.to_bus
				}
			}
		}
		dests.sort()
		if rx_by_msg.len == 0 && tx_by_msg.len == 0 && conns.len == 0 && my_routes.len == 0 {
			continue
		}
		bus_names << bname
		bus_dests[bname] = dests

		// io fn needs a timestamp to gate tx, monitor rx deadlines, or pace ISO-TP
		mut uses_now := tx_by_msg.len > 0 || conns.len > 0
		for msg, _ in rx_by_msg {
			if (rx_timeout_us[msg] or { 0 }) > 0 {
				uses_now = true
			}
		}

		glue << ''
		glue << 'struct Bridge_${bb}_state {'
		glue << 'mut:'
		glue << '\tchan can.Channel'
		for msg, _ in tx_by_msg {
			glue << '\ttx_${msg}_st com.TxState'
			if e2e_on[msg] or { false } {
				glue << '\te2e_tx_${msg} e2e.TxState'
			}
			if secoc_on[msg] or { false } {
				glue << '\tsecoc_key_${msg} secoc.Key'
				glue << '\tsecoc_tx_${msg} secoc.TxState'
			}
		}
		for msg, _ in rx_by_msg {
			if (rx_timeout_us[msg] or { 0 }) > 0 {
				glue << '\trx_${msg}_st com.RxState'
			}
			if e2e_on[msg] or { false } {
				glue << '\te2e_rx_${msg} e2e.RxState'
			}
			if secoc_on[msg] or { false } {
				glue << '\tsecoc_key_${msg} secoc.Key'
				glue << '\tsecoc_rx_${msg} secoc.RxState'
			}
		}
		for c in conns {
			tp := snake(c.name)
			glue << '\ttp_${tp} isotp.Link'
			glue << '\ttp_${tp}_buf [isotp.max_payload]u8'
			glue << '\tuds_${tp} uds.Server'
			glue << '\tuds_${tp}_resp [64]u8'
		}
		for d in dests {
			glue << '\troute_${snake(d)} can.Channel // gateway: forward to ${d}'
		}
		glue << '}'
		glue << ''
		glue << 'fn io_${bb}_10ms(ctx voidptr) {'
		glue << '\tmut st := unsafe { &Bridge_${bb}_state(ctx) }'
		if uses_now {
			glue << '\tnow := osal.now_us()'
		}
		if rx_by_msg.len > 0 || conns.len > 0 || my_routes.len > 0 {
			glue << '\tmut rx := can.Frame{}'
			glue << '\tfor st.chan.recv(mut rx) {'
			for r in my_routes {
				// raw-PDU gateway: forward the frame to another bus, unchanged
				// (optionally remapping the id), without decoding it to signals.
				glue << '\t\tif rx.id == u32(0x${r.from_id.hex()}) {'
				glue << '\t\t\tmut fwd := rx'
				if r.to_id != r.from_id {
					glue << '\t\t\tfwd.id = u32(0x${r.to_id.hex()})'
				}
				glue << '\t\t\tst.route_${snake(r.to_bus)}.send(fwd)'
				glue << '\t\t}'
			}
			for msg, list in rx_by_msg {
				// require the received length to match the PDU DLC — recv copies only
				// the actual bytes into the reused frame, so a short same-id frame
				// would otherwise be decoded over stale trailing bytes.
				glue << '\t\tif rx.id == ${msg}_id && rx.len == ${msg}_dlc {'
				e2e := e2e_on[msg] or { false }
				secoc := secoc_on[msg] or { false }
				// protected frames are decoded only if the check passes; a bad frame
				// is ignored (the rx deadline then invalidates).
				mut ind := '\t\t\t'
				if secoc {
					glue << '\t\t\tif st.secoc_rx_${msg}.verify(&st.secoc_key_${msg}, &rx.data[0], int(${msg}_dlc), u16(0x${(secoc_id[msg] or { 0 }).hex()}), ${secoc_fresh[msg] or { 0 }}, ${secoc_mac[msg] or { 0 }}, ${secoc_maclen[msg] or { 0 }}).usable() {'
					ind = '\t\t\t\t'
				} else if e2e {
					glue << '\t\t\tif st.e2e_rx_${msg}.check(&rx.data[0], int(${msg}_dlc), u16(0x${(e2e_id[msg] or { 0 }).hex()}), ${e2e_crc[msg] or { 0 }}, ${e2e_ctr[msg] or { 0 }}).usable() {'
					ind = '\t\t\t\t'
				}
				for sname in list {
					si := sig_of[sname] or { continue }
					fld := snake(sname)
					dec := '${si.dbc_msg}_${snake(sname)}_phys(rx.data)'
					valassign := if si.val_type == 'bool' {
						'${si.val_field}: ${dec} != 0.0'
					} else {
						'${si.val_field}: ${si.val_type}(${dec})'
					}
					validassign := if si.has_valid { ', valid: true' } else { '' }
					glue << '${ind}mut ${fld} := sig.${sname}{ ${valassign}${validassign} }'
					glue << '${ind}osal.${publish_fn(si.transport)}(${fld}_ch, &${fld}, u8(sizeof(${fld})))'
				}
				if (rx_timeout_us[msg] or { 0 }) > 0 {
					glue << '${ind}st.rx_${msg}_st.on_receive(now)'
				}
				if secoc || e2e {
					glue << '\t\t\t}'
				}
				glue << '\t\t}'
			}
			for c in conns {
				tp := snake(c.name)
				glue << '\t\tif rx.id == u32(0x${c.rx_id.hex()}) {'
				glue << '\t\t\tmut p_${tp} := isotp.Pdu{}'
				glue << '\t\t\tfor i in 0 .. 8 {'
				glue << '\t\t\t\tp_${tp}.data[i] = rx.data[i]'
				glue << '\t\t\t}'
				glue << '\t\t\tst.tp_${tp}.on_frame(now, p_${tp})'
				glue << '\t\t}'
			}
			glue << '\t}'
			// rx deadline crossed -> publish invalid (valid=false) signals, once
			for msg, list in rx_by_msg {
				if (rx_timeout_us[msg] or { 0 }) > 0 {
					glue << '\tif st.rx_${msg}_st.expired(now) {'
					for sname in list {
						si := sig_of[sname] or { continue }
						fld := snake(sname)
						glue << '\t\tmut ${fld} := sig.${sname}{}'
						glue << '\t\tosal.${publish_fn(si.transport)}(${fld}_ch, &${fld}, u8(sizeof(${fld})))'
					}
					glue << '\t}'
				}
			}
			// ISO-TP + UDS: refresh live-signal DIDs, dispatch a reassembled
			// request, drain the segmented response.
			for c in conns {
				tp := snake(c.name)
				for idx, did in dids {
					if did.signal == '' {
						continue
					}
					si := sig_of[did.signal] or { continue }
					f := snake(did.signal)
					glue << '\tmut ${f}_did := sig.${did.signal}{}'
					glue << '\tif osal.${acquire_fn(si.transport)}(${f}_ch, &${f}_did, u8(sizeof(${f}_did))) {'
					glue << did_signal_encode(tp, idx, '${f}_did.${si.val_field}', si.val_type)
					glue << '\t}'
				}
				glue << '\t${tp}_n := st.tp_${tp}.take(&st.tp_${tp}_buf[0])'
				glue << '\tif ${tp}_n > 0 {'
				glue << '\t\t${tp}_rlen := st.uds_${tp}.handle(&st.tp_${tp}_buf[0], ${tp}_n, &st.uds_${tp}_resp[0])'
				glue << '\t\tif ${tp}_rlen > 0 {'
				glue << '\t\t\tst.tp_${tp}.send(&st.uds_${tp}_resp[0], ${tp}_rlen)'
				glue << '\t\t}'
				glue << '\t}'
				glue << '\tmut pdu_${tp} := isotp.Pdu{}'
				glue << '\tfor st.tp_${tp}.poll(now, mut pdu_${tp}) {'
				glue << '\t\tmut cf_${tp} := can.Frame{'
				glue << '\t\t\tid:  u32(0x${c.tx_id.hex()})'
				glue << '\t\t\tlen: 8'
				glue << '\t\t}'
				glue << '\t\tfor i in 0 .. 8 {'
				glue << '\t\t\tcf_${tp}.data[i] = pdu_${tp}.data[i]'
				glue << '\t\t}'
				glue << '\t\tst.chan.send(cf_${tp})'
				glue << '\t}'
			}
		}
		for msg, list in tx_by_msg {
			glue << '\tmut tx_${msg} := can.Frame{'
			glue << '\t\tid:  ${msg}_id'
			glue << '\t\tlen: ${msg}_dlc'
			glue << '\t}'
			glue << '\tmut tx_${msg}_any := false'
			for sname in list {
				si := sig_of[sname] or { continue }
				fld := snake(sname)
				phys := if si.val_type == 'bool' {
					'if ${fld}.${si.val_field} { f64(1) } else { f64(0) }'
				} else {
					'f64(${fld}.${si.val_field})'
				}
				glue << '\tmut ${fld} := sig.${sname}{}'
				glue << '\tif osal.${acquire_fn(si.transport)}(${fld}_ch, &${fld}, u8(sizeof(${fld}))) {'
				glue << '\t\t${si.dbc_msg}_${snake(sname)}_set(mut tx_${msg}.data, ${phys})'
				glue << '\t\ttx_${msg}_any = true'
				glue << '\t}'
			}
			glue << '\tif tx_${msg}_any && st.tx_${msg}_st.should_send(now, tx_${msg}.data, ${msg}_dlc) {'
			if e2e_on[msg] or { false } {
				// stamp CRC + counter after the change decision (so the counter
				// doesn't make every frame look "changed" to on-change modes)
				glue << '\t\tst.e2e_tx_${msg}.protect(&tx_${msg}.data[0], int(${msg}_dlc), u16(0x${(e2e_id[msg] or { 0 }).hex()}), ${e2e_crc[msg] or { 0 }}, ${e2e_ctr[msg] or { 0 }})'
			}
			if secoc_on[msg] or { false } {
				// authenticate: stamp freshness + truncated AES-CMAC after the change decision
				glue << '\t\tst.secoc_tx_${msg}.protect(&st.secoc_key_${msg}, &tx_${msg}.data[0], int(${msg}_dlc), u16(0x${(secoc_id[msg] or { 0 }).hex()}), ${secoc_fresh[msg] or { 0 }}, ${secoc_mac[msg] or { 0 }}, ${secoc_maclen[msg] or { 0 }})'
			}
			glue << '\t\tst.chan.send(tx_${msg})'
			glue << '\t}'
		}
		glue << '}'
		glue << ''
		mut psig := 'ch can.Channel'
		for d in dests {
			psig += ', route_${snake(d)} can.Channel'
		}
		glue << 'pub fn partition_${bb}(${psig}) {'
		glue << '\tosal.pin_to_core(${bus_core[bname] or { 0 }})'
		glue << '\tmut st := Bridge_${bb}_state{'
		glue << '\t\tchan: ch'
		glue << '\t}'
		for d in dests {
			glue << '\tst.route_${snake(d)} = route_${snake(d)}'
		}
		for msg, _ in tx_by_msg {
			mode := tx_mode[msg] or { 'cyclic' }
			mut cyc := tx_cycle_us[msg] or { 0 }
			if cyc == 0 {
				cyc = 100000 // default cyclic period when unspecified
			}
			glue << '\tst.tx_${msg}_st = com.TxState{'
			glue << '\t\tmode: com.TxMode.${mode}'
			glue << '\t\tcycle_us: ${cyc}'
			glue << '\t\tmin_delay_us: ${tx_min_us[msg] or { 0 }}'
			glue << '\t}'
			if secoc_on[msg] or { false } {
				glue << '\tst.secoc_key_${msg} = secoc.new_key(${byte16_lit(secoc_key[msg] or { []u8{} })})'
			}
		}
		for msg, _ in rx_by_msg {
			if (rx_timeout_us[msg] or { 0 }) > 0 {
				glue << '\tst.rx_${msg}_st = com.RxState{'
				glue << '\t\ttimeout_us: ${rx_timeout_us[msg]}'
				glue << '\t}'
			}
			if secoc_on[msg] or { false } {
				glue << '\tst.secoc_key_${msg} = secoc.new_key(${byte16_lit(secoc_key[msg] or { []u8{} })})'
			}
		}
		for c in conns {
			tp := snake(c.name)
			glue << '\tst.tp_${tp} = isotp.Link{'
			glue << '\t\tbs:    ${c.bs}'
			glue << '\t\tstmin: ${c.stmin}'
			glue << '\t}'
			glue << '\tst.uds_${tp} = uds.Server{}'
			for idx, did in dids {
				glue << '\tst.uds_${tp}.dids[${idx}] = uds.Did{'
				glue << '\t\tid: u16(0x${did.id.hex()})'
				if did.writable {
					glue << '\t\twritable: true'
				}
				glue << '\t}'
				for bi, b in did.bytes {
					glue << '\tst.uds_${tp}.dids[${idx}].data[${bi}] = u8(0x${b.hex()})'
				}
				if did.bytes.len > 0 {
					glue << '\tst.uds_${tp}.dids[${idx}].len = ${did.bytes.len}'
				}
			}
			glue << '\tst.uds_${tp}.ndid = ${dids.len}'
		}
		glue << '\tmut sched := loom.Scheduler{}'
		glue << '\tsched.every(10_000, io_${bb}_10ms, &st)'
		glue << '\tfor {'
		glue << '\t\tloom_t0 := osal.now_us()'
		glue << '\t\tsched.run(loom_t0)'
		glue << '\t\tloom_t1 := osal.now_us()'
		glue << '\t\tsched.account(loom_t1 - loom_t0, loom_t1) // per-core load'
		if telem_on && 'b:${bname}' in telem_slot {
			glue << '\t\tosal.scratch_set(${telem_slot['b:${bname}']}, u64(sched.load_permille()))'
		}
		glue << '\t\tosal.sleep_us(1000)'
		glue << '\t}'
		glue << '}'
	}

	// --- telemetry tx: sum per-partition load by core -> CpuLoad frame on the bus ---
	// (host only: a spawned tx thread reading the per-core scratch slots. Target mode
	// sends the CpuLoad frame inline from run(), reading load_permille() directly.)
	if telem_on && telem_iface != '' && !target_on {
		mut ncores := 0
		for sc in slot_core {
			if sc + 1 > ncores {
				ncores = sc + 1
			}
		}
		glue << ''
		glue << 'fn partition_telem() {'
		glue << '\tosal.pin_to_core(${bus_core[telem_bus] or { 0 }})'
		glue << '\tmut c := can.Channel{}'
		glue << "\tif !c.open('${telem_iface}', false) {"
		glue << '\t\treturn'
		glue << '\t}'
		glue << '\tfor {'
		glue << '\t\tmut load := [8]u16{}'
		for cc in 0 .. ncores {
			mut terms := []string{}
			for slot, sc in slot_core {
				if sc == cc {
					terms << 'u16(osal.scratch_get(${slot}))'
				}
			}
			if terms.len > 0 {
				glue << '\t\tload[${cc}] = ${terms.join(' + ')}'
			}
		}
		glue << '\t\tframe := telem.encode_cpuload(load, ${ncores})'
		glue << '\t\tmut f := can.Frame{'
		glue << '\t\t\tid:  u32(0x${telem_id.hex()})'
		glue << '\t\t\tlen: 8'
		glue << '\t\t}'
		glue << '\t\tfor i in 0 .. 8 {'
		glue << '\t\t\tf.data[i] = frame[i]'
		glue << '\t\t}'
		glue << '\t\tc.send(f)'
		glue << '\t\tosal.sleep_us(${telem_period_us})'
		glue << '\t}'
		glue << '}'
	}

	bus_names.sort()
	if target_on {
		// --- target run(): one inline single-core superloop. No spawn, no osal. The
		//     timebase is the board's DWT clock (board_now_us); the loop paces to a
		//     fixed tick so idle time between passes is real idle (the Loom measures
		//     load as run-time / wall-clock, so unpaced spinning would read ~50%). The
		//     CpuLoad frame is sent inline from load_permille() — no scratch, no tx
		//     thread. Takes the telemetry bus channel (main.v opens it after board init).
		if by_part.keys().len != 1 {
			panic('loom2v: [target] baremetal supports exactly one partition (got ${by_part.keys().len})')
		}
		part := by_part.keys()[0]
		chp := snake(telem_bus)
		glue << ''
		glue << 'fn C.board_now_us() u64 // bare-metal monotonic µs (DWT cycle counter)'
		glue << ''
		glue << 'pub fn run(${chp} can.Channel) {'
		glue << '\tmut ch := ${chp}'
		glue << '\tmut st := Partition_${part}_state{}'
		glue << '\tmut sched := loom.Scheduler{}'
		for r in all_regs[part] or { []string{} } {
			glue << r
		}
		if telem_on && telem_iface != '' {
			glue << '\tmut load := [8]u16{}'
			glue << '\ttelem_period_us := u64(${telem_period_us})'
			glue << '\tmut last_telem := u64(0)'
			if telem_detail_id != 0 {
				glue << '\tmut last_overruns := u32(0) // for the per-period overrun count'
			}
		}
		glue << '\ttick_us := u64(${target_tick_us})'
		glue << '\tmut next_tick := C.board_now_us() + tick_us'
		glue << '\tfor {'
		glue << '\t\tt0 := C.board_now_us()'
		glue << '\t\tsched.run(t0)'
		glue << '\t\tt1 := C.board_now_us()'
		glue << '\t\tsched.account(t1 - t0, t1) // handler time -> this core\'s load'
		glue << '\t\tif t1 - t0 > tick_us { // pass exceeded its tick budget -> overrun'
		glue << '\t\t\tsched.mark_overrun()'
		glue << '\t\t}'
		if telem_on && telem_iface != '' {
			glue << '\t\tif t1 - last_telem >= telem_period_us {'
			glue << '\t\t\tlast_telem = t1'
			glue << '\t\t\tload[0] = sched.load_permille() // single M7 -> core 0 only'
			glue << '\t\t\tframe := telem.encode_cpuload(load, 1)'
			glue << '\t\t\tmut f := can.Frame{'
			glue << '\t\t\t\tid:  u32(0x${telem_id.hex()})'
			glue << '\t\t\t\tlen: 8'
			glue << '\t\t\t}'
			glue << '\t\t\tfor i in 0 .. 8 {'
			glue << '\t\t\t\tf.data[i] = frame[i]'
			glue << '\t\t\t}'
			glue << '\t\t\tch.send(f)'
			if telem_detail_id != 0 {
				glue << '\t\t\tovr := sched.overruns()'
				glue << '\t\t\tdetail := telem.encode_loaddetail(sched.load_permille_100ms(),'
				glue << '\t\t\t\tsched.load_permille_1s(), sched.load_permille_10s(), ovr - last_overruns)'
				glue << '\t\t\tlast_overruns = ovr'
				glue << '\t\t\tmut d := can.Frame{'
				glue << '\t\t\t\tid:  u32(0x${telem_detail_id.hex()})'
				glue << '\t\t\t\tlen: 8'
				glue << '\t\t\t}'
				glue << '\t\t\tfor i in 0 .. 8 {'
				glue << '\t\t\t\td.data[i] = detail[i]'
				glue << '\t\t\t}'
				glue << '\t\t\tch.send(d)'
			}
			glue << '\t\t}'
		}
		glue << '\t\tfor C.board_now_us() < next_tick {} // idle to the tick (real idle)'
		glue << '\t\tnext_tick += tick_us'
		glue << '\t\tnow := C.board_now_us()'
		glue << '\t\tif now > next_tick { // a pass overran the tick — resync'
		glue << '\t\t\tnext_tick = now + tick_us'
		glue << '\t\t}'
		glue << '\t}'
		glue << '}'
	} else {
		// --- host run(): launch every bus bridge + app partition, then wait. One
		//     Channel param per bus (sorted for a stable signature main.v can rely on). ---
		glue << ''
		mut waits := []string{}
		if bus_names.len == 0 {
			glue << 'pub fn run() {'
		} else {
			mut params := []string{}
			for b in bus_names {
				params << '${snake(b)} can.Channel'
			}
			glue << 'pub fn run(${params.join(', ')}) {'
			for b in bus_names {
				bb := snake(b)
				mut spawn_args := bb
				for d in bus_dests[b] or { []string{} } {
					spawn_args += ', ${snake(d)}'
				}
				glue << '\tt_${bb} := spawn partition_${bb}(${spawn_args})'
				waits << 't_${bb}'
			}
		}
		for part, _ in by_part {
			glue << '\tt_${part} := spawn partition_${part}(${core_of[part] or { 0 }}, unsafe { nil })'
			waits << 't_${part}'
		}
		if telem_on && telem_iface != '' {
			glue << '\tt_telem := spawn partition_telem()'
			waits << 't_telem'
		}
		for w in waits {
			glue << '\t${w}.wait()'
		}
		glue << '}'
	}

	os.write_file(args[3], signals.join('\n') + '\n') or { panic('write ${args[3]}: ${err}') }
	os.write_file(args[4], ports.join('\n') + '\n') or { panic('write ${args[4]}: ${err}') }
	os.write_file(args[5], glue.join('\n') + '\n') or { panic('write ${args[5]}: ${err}') }
	eprintln('loom2v: ${sig_names.len} signals (${bus_names.len} bus bridge), ${isotp_conns.len} isotp, ${by_part.len} partition(s)')
}

// did_signal_encode emits the big-endian write of a live signal value into a
// DID's data buffer (per the signal's value-field type).
fn did_signal_encode(tp string, idx int, expr string, val_type string) string {
	d := 'st.uds_${tp}.dids[${idx}]'
	return match val_type {
		'u16' {
			'\t\t${d}.data[0] = u8(${expr} >> 8)\n\t\t${d}.data[1] = u8(${expr})\n\t\t${d}.len = 2'
		}
		'u32' {
			'\t\t${d}.data[0] = u8(${expr} >> 24)\n\t\t${d}.data[1] = u8(${expr} >> 16)\n\t\t${d}.data[2] = u8(${expr} >> 8)\n\t\t${d}.data[3] = u8(${expr})\n\t\t${d}.len = 4'
		}
		'bool' {
			'\t\t${d}.data[0] = if ${expr} { u8(1) } else { u8(0) }\n\t\t${d}.len = 1'
		}
		else {
			'\t\t${d}.data[0] = u8(${expr})\n\t\t${d}.len = 1'
		}
	}
}

// byte16_lit renders 16 bytes as a V fixed-array literal `[u8(0x..), 0x.., ...]!`
// (zero-padded), for a generated secoc.new_key(...) call.
fn byte16_lit(b []u8) string {
	mut parts := []string{}
	for i in 0 .. 16 {
		v := if i < b.len { b[i] } else { u8(0) }
		parts << if i == 0 { 'u8(0x${v.hex()})' } else { '0x${v.hex()}' }
	}
	return '[${parts.join(', ')}]!'
}

// parse_hex turns "01 0A FF" into bytes.
fn parse_hex(s string) []u8 {
	mut out := []u8{}
	for part in s.split(' ') {
		if part != '' {
			out << hexbyte(part)
		}
	}
	return out
}

fn hexbyte(s string) u8 {
	mut v := 0
	for c in s {
		v *= 16
		if c >= `0` && c <= `9` {
			v += int(c - `0`)
		} else if c >= `a` && c <= `f` {
			v += int(c - `a`) + 10
		} else if c >= `A` && c <= `F` {
			v += int(c - `A`) + 10
		}
	}
	return u8(v)
}

// dbc_dlc_of returns the DLC (byte length) of the message whose snake-name is `key`.
fn dbc_dlc_of(db candb.Database, key string) ?int {
	for m in db.messages {
		if snake(m.name) == key {
			return int(m.dlc)
		}
	}
	return none
}

// dbc_id_of returns the CAN id of the message whose snake-name is `key`.
fn dbc_id_of(db candb.Database, key string) ?int {
	for m in db.messages {
		if snake(m.name) == key {
			return int(m.id)
		}
	}
	return none
}

// dbc_message_of returns snake(message name) of the DBC message carrying `sig`.
fn dbc_message_of(db candb.Database, signame string) ?string {
	for m in db.messages {
		for s in m.signals {
			if s.name == signame {
				return snake(m.name)
			}
		}
	}
	return none
}

fn provenance(name string, sig_of map[string]SigInfo) string {
	s := sig_of[name] or { return '\t// signal "${name}"' }
	if s.local {
		return '\t// signal "${name}" — local cell in partition "${s.from}"'
	}
	return '\t// signal "${name}" — ch, transport ${s.transport}, ${s.from} -> ${s.to}'
}

fn acquire_fn(tr string) string {
	return match tr {
		'seqlock' { 'ioc_read' }
		'triple' { 'ioc_acquire' }
		else { 'ioc_acquire2' }
	}
}

fn publish_fn(tr string) string {
	return match tr {
		'seqlock' { 'ioc_write' }
		'triple' { 'ioc_publish' }
		else { 'ioc_publish2' }
	}
}

fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			if (prev >= `a` && prev <= `z`) || (prev >= `0` && prev <= `9`) {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}
