// loom2v's cross-core signal emission — the xioc half of multi-image generation.
//
// There is NO config here: a signal whose `from` partition lives in another image is
// REMOTE (derived in build_model, docs/multi-image.md), and every remote signal gets an
// xioc slot (boards/common/xioc.h) in declaration order. This file owns:
//   - gen/duo_gen.h — the ONE contract header both images compile against (the satellite
//     publishes via duo_pub(DUO_SLOT_<NAME>, ...); the bus owner polls the same slots;
//     slot numbers appear nowhere else),
//   - the bus-owning image's reader->CAN wiring: a fresh-gated, period-paced transmit of
//     each frame-bound remote signal inside the comm loop (via C.duo_poll, the xioc
//     reader living in comm_glue.c),
//   - the satellite trace forwarding (dtrace handoff cell: arm / freeze+snapshot / import)
//     — gated on satellite PARTITIONS existing, not on signals,
//   - the manifest's `# duo signals` rows.
//
// A remote signal `to = <bus>` is transmitted here; `to = <local partition>` is a slot
// with no generated consumer (platform C — shell m4sig/iocx — reads it via the header).
module main

// duo_on: any cross-image signal slots to wire.
fn duo_on(m Model) bool {
	return m.duo_names.len > 0
}

// has_satellite: any partition whose image lives elsewhere (hand-written or generated) —
// the gate for trace forwarding, which exists per CORE, not per signal.
fn has_satellite(m Model) bool {
	for _, ext in m.part.external {
		if ext {
			return true
		}
	}
	return false
}

// duo_gen_h: the generated cross-core contract header — slots appear ONLY here.
fn duo_gen_h(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	g << '/* generated by loom2v from ecu.toml — do not edit. The cross-core signal contract:'
	g << ' * BOTH images compile against these slot assignments (the satellite publishes via'
	g << ' * duo_pub(DUO_SLOT_<NAME>, ...); the bus owner polls the same slots). */'
	g << '#ifndef BLOBLY_DUO_GEN_H'
	g << '#define BLOBLY_DUO_GEN_H'
	for sname in m.duo_names {
		g << '#define DUO_SLOT_${snake(sname).to_upper()} ${m.duo_idx[sname] or { 0 }}'
	}
	g << '#define DUO_GEN_SLOTS ${m.duo_names.len}'
	g << '#endif'
	return g
}

fn duo_c_decls(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	return ['fn C.duo_poll(int, &u32, &u32) int // xioc reader (comm_glue.c): 1 = fresh value']
}

// duo_comm_locals: per-frame-bound-signal pacing state in the comm thread.
fn duo_comm_locals(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		if si.external {
			g << '\tmut duo_${snake(sname)}_last := u64(0)'
			g << '\tmut duo_${snake(sname)}_a := u32(0)'
			g << '\tmut duo_${snake(sname)}_b := u32(0)'
		}
	}
	if g.len > 0 {
		g.prepend('\t// cross-core signals (gen_duo): last tx time + latest polled value per signal')
		g << '\tmut duo_txf := can.Frame{}'
	}
	return g
}

// duo_produce_drain: poll each slot and transmit frame-bound signals on their period,
// fresh-gated — a stale satellite (or a dead core) simply goes quiet on the bus.
fn duo_produce_drain(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		if !si.external {
			continue // slot-only (satellite -> local partition): no CAN tx
		}
		slot := m.duo_idx[sname] or { 0 }
		mut cyc := m.frames.tx_cycle_us[si.dbc_msg] or { 0 }
		if cyc <= 0 {
			cyc = 100000 // default cyclic 100 ms if no [[frame]].tx.cycle_ms
		}
		n := snake(sname)
		g << '\t\tif C.duo_poll(${slot}, &duo_${n}_a, &duo_${n}_b) != 0'
		g << '\t\t\t&& t1 - duo_${n}_last >= u64(${cyc}) && ch.tx_ready() {'
		g << '\t\t\tduo_txf.id = u32(0x${si.dbc_id.hex()})'
		g << '\t\t\tduo_txf.len = ${si.dbc_dlc}'
		g << '\t\t\tduo_txf.data[0] = u8(duo_${n}_a)'
		g << '\t\t\tduo_txf.data[1] = u8(duo_${n}_a >> 8)'
		g << '\t\t\tduo_txf.data[2] = u8(duo_${n}_a >> 16)'
		g << '\t\t\tduo_txf.data[3] = u8(duo_${n}_a >> 24)'
		if si.dbc_dlc == 8 {
			g << '\t\t\tduo_txf.data[4] = u8(duo_${n}_b)'
			g << '\t\t\tduo_txf.data[5] = u8(duo_${n}_b >> 8)'
			g << '\t\t\tduo_txf.data[6] = u8(duo_${n}_b >> 16)'
			g << '\t\t\tduo_txf.data[7] = u8(duo_${n}_b >> 24)'
		}
		g << '\t\t\tch.send(duo_txf)'
		g << '\t\t\tduo_${n}_last = t1'
		g << '\t\t}'
	}
	return g
}

// duo trace forwarding — the multi-core dump. Emitted only when a SATELLITE PARTITION and
// an ISO-TP [trace] are both on: the rx arm forwards satellite-targeted commands (core-mask
// bit 1) into the dtrace handoff cell, and the comm loop imports the acked snapshot as the
// remote dump block (TraceModule.load_remote → streamed after the local blocks).
fn duo_trace_on(m Model) bool {
	return has_satellite(m) && m.trace.on && m.trace.dump_fc_id != 0
}

fn duo_trace_c_decls(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'fn C.duo_trace_req(u32) // post arm(1)/snapshot(2) to the satellite (duo.h dtrace cell)',
		'fn C.duo_trace_ready() int',
		'fn C.duo_trace_count() u32',
		'fn C.duo_trace_buf() &u8',
	]
}

fn duo_trace_globals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return ["\tg_duo_trace_ring [${m.trace.buffer_records}]trace.Record // the satellite core's imported dump window"]
}

fn duo_trace_locals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\tg_tm.set_remote(u8(1), &g_duo_trace_ring[0], ${m.trace.buffer_records}) // satellite blocks ride our dump link',
		'\tmut duo_trc_wait := false // a satellite snapshot was requested by op_dump',
	]
}

// the rx-arm extension: parse the SAME trace cmd frame the module gets; bit 1 of the core
// mask (data[6]) addresses the satellite. arm/reset forward as arm; stop forwards as
// freeze+snapshot (so the window is frozen close to the local one); dump waits for the ack.
fn duo_trace_rx_arm(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\t\tif rx.id == u32(0x${m.trace.cmd_id.hex()}) && rx.len == 8 && rx.data[6] & 0x02 != 0 {',
		'\t\t\t\tmatch rx.data[0] {',
		'\t\t\t\t\t1, 2, 4 { C.duo_trace_req(1) } // arm/start/reset -> satellite arm',
		'\t\t\t\t\t3 { C.duo_trace_req(2) } // stop -> satellite freeze+snapshot',
		'\t\t\t\t\t6 { duo_trc_wait = true } // dump -> import the ack below',
		'\t\t\t\t\telse {}',
		'\t\t\t\t}',
		'\t\t\t}',
	]
}

fn duo_trace_poll(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\tif duo_trc_wait && C.duo_trace_ready() != 0 {',
		'\t\t\tg_tm.load_remote(C.duo_trace_buf(), C.duo_trace_count())',
		'\t\t\tduo_trc_wait = false',
		'\t\t}',
	]
}

fn duo_manifest(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := ['# duo signals: name,slot,frame']
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		fr := if si.external { '0x${si.dbc_id.hex()}' } else { '-' }
		g << '${sname},${m.duo_idx[sname] or { 0 }},${fr}'
	}
	return g
}
