// loom2v's satellite image emitter — the multi-image half (docs/multi-image.md).
//
// A [[partition]] with image = "<dir>" gets its WHOLE image generated into that directory
// by the same run that generates the bus owner: sig/signals_gen.v + ports/ports_gen.v +
// gen/loom_gen.v (+ gen/loom_build.mk). The emitted image is the ThreadX shape the
// hand-written examples/h755_m4_app pioneered: park on clocks-ready, DWT timebase, xioc
// pool init, this core's OWN trace recorder (trace_hooks.c, armed from boot), one kernel
// thread + Loom scheduler per [[partition.thread]], handler wrappers whose remote writes
// publish via duo_pub, and the dtrace handoff serviced from the first (highest-priority)
// thread's loop. The example keeps main.v (a gen.boot() shim), its app/ FBs, its glue C,
// and its Makefile — exactly the split every example has.
//
// Nothing here is core-kind-specific: arch flags live in the satellite's Makefile/boards
// layer; this emitter only knows partitions, threads, and signal crossings. A future SMP
// target simply derives ZERO image partitions and none of this runs.
module main

import os
import toml

// emit_satellite_images writes one generated image per `image =` partition. The image dir
// is relative to the OWNER's ecu.toml (loom2v itself runs from the repo root, so a bare
// relative path would escape the example). ecu is the owner's ecu.toml path (banner).
fn emit_satellite_images(m Model, doc toml.Doc, producers []Producer, ecu string) {
	// The one-satellite-producer guard lives in build_model (it must count hand-written
	// external satellites too, which never reach this emitter — codex #211 r10).
	for part, rel in m.part.image {
		img := os.norm_path(os.join_path(os.dir(ecu), rel))
		if !m.target.threadx {
			panic('loom2v: partition "${part}" has image = "${rel}", but satellite images are ' +
				'generated for the ThreadX target only')
		}
		threads := m.part.threads_of[part] or {
			panic('loom2v: image partition "${part}" declares no threads')
		}
		// the satellite pass of the SAME handler emitter the owner uses: state structs,
		// port structs, wrappers (remote writes -> duo_pub), registration lines.
		sat_ports, sat_glue, sat_regs := emit_handlers(m, producers, map[string]int{}, false,
			part)

		mut g := []string{}
		g << '// Code generated by tools/loom2v from ${os.file_name(ecu)} (partition "${part}",'
		g << '// image = "${img}") — DO NOT EDIT. The bus owner\'s generator run owns this file:'
		g << '// regenerate from the OWNER example (its ecu.toml declares this whole node).'
		g << 'module gen'
		g << ''
		mut imports := ['ports', 'app', 'loom']
		if sat_glue.join('\n').contains('sig.') {
			imports.prepend('sig')
		}
		for im in imports {
			g << 'import ${im}'
		}
		g << sat_glue
		g << ''
		g << '// this image owns NO clocks, NO pins, NO bus — the owner core brings those up.'
		g << 'fn C.board_now_us() u64 // DWT-based µs (this core\'s own counter, glue C)'
		g << 'fn C.duo_wait_clocks() // park until the owner signals clocks-ready (duo.h)'
		g << 'fn C.board_timebase_init()'
		g << 'fn C.duo_ioc_init() // the shared xioc pool (satellite is the writer side)'
		// THIS partition's production decides the handshake role: only the PRODUCING
		// satellite publishes the layout id — a non-producing image writing the cell
		// would be a second writer, and could restore the id while the real producer
		// is stopped, opening polling onto retained payloads (codex #211 r11).
		mut produces := false
		mut wide_writes := []string{}
		for sname in m.duo_names {
			si := m.sig_of[sname] or { continue }
			if si.from == part {
				produces = true
				if si.wide {
					wide_writes << sname
				}
			}
		}
		if produces {
			g << 'fn C.duo_layout_publish() // layout-id handshake: owner polls nothing until this'
		}
		g << 'fn C.duo_pub(int, u32, u32) // xioc writer — slots from gen/duo_gen.h'
		if wide_writes.len > 0 {
			g << 'fn C.duo_xw_init(u32, u32) // wide xioc_n channel init (writer side, boot)'
			g << 'fn C.duo_pub_n(u32, &u32) // wide xioc_n writer — offsets from gen/duo_gen.h'
		}
		g << 'fn C._tx_thread_sleep(u32) u32'
		g << 'fn C._tx_initialize_kernel_enter()'
		g << 'fn C._tx_thread_create(voidptr, &char, fn (u32), u32, voidptr, u32, u32, u32, u32, u32) u32'
		fb_traced := m.trace.on && m.trace.level == 'all'
		if m.trace.on {
			g << 'fn C.trace_arm() // this core\'s recorder free-runs; the owner re-arms per session'
			g << 'fn C.trace_bind_thread(voidptr)'
			g << 'fn C.duo_trace_service() // the dtrace handoff (owner posts, we snapshot/ack)'
		}
		if fb_traced {
			g << 'fn C.trace_fb(u32, u64, u32)'
			// the same GLOBAL handler-id tables the owner emits — the walk covers every
			// partition, so satellite handlers land on their manifest ids.
			g << trace_fb_hooks(m, doc, threads, true)
		}
		g << ''
		g << '__global ('
		for thr in threads {
			g << '\tg_${thr}_tcb   [32]u64  // >= sizeof(TX_THREAD) (200 B), 8-byte aligned'
			g << '\tg_${thr}_stack [4096]u8'
			g << '\tg_sched_${thr} loom.Scheduler // bss, never an entry-frame local'
		}
		g << ')'
		for ti, thr in threads {
			g << ''
			g << 'fn run_${thr}() {'
			g << '\tmut st := Thread_${thr}_state{} // small + carries the FB field defaults: stack is right'
			g << '\tmut sched := &g_sched_${thr} // module-sized: lives in bss, not this lifetime frame'
			for r in sat_regs['${part}/${thr}'] or { []string{} } {
				g << r
			}
			g << '\ttick_us := u64(${m.target.tick_us})'
			if fb_traced {
				g << '\tsched.set_trace_hook(trace_fb_hook_${thr}, unsafe { nil })'
			}
			g << '\tfor {'
			g << '\t\tt0 := C.board_now_us()'
			if fb_traced {
				g << '\t\tsched.run_profiled(trace_clock)'
				g << '\t\tt1 := C.board_now_us()'
			} else {
				g << '\t\tsched.run(t0)'
				g << '\t\tt1 := C.board_now_us()'
				g << "\t\tsched.account(t1 - t0, t1) // handler time -> this thread's load"
			}
			g << '\t\tif t1 - t0 > tick_us { // pass exceeded its tick budget -> overrun'
			g << '\t\t\tsched.mark_overrun()'
			g << '\t\t}'
			if ti == 0 && m.trace.on {
				g << '\t\tC.duo_trace_service() // ~one poll per tick: plenty for the dump handshake'
			}
			if ti == 0 && produces {
				g << '\t\tC.duo_layout_publish() // REPUBLISH per tick: the owner retracts the id at ITS'
				g << '\t\t// boot (SRAM survives an owner-only reset — a retained id + retained channels'
				g << '\t\t// would replay one stale frame); a live satellite restores it within a tick'
			}
			g << '\t\tC._tx_thread_sleep(u32(1))'
			g << '\t}'
			g << '}'
		}
		g << ''
		for thr in threads {
			g << 'fn ${thr}_thread_entry(input u32) {'
			g << '\trun_${thr}()'
			g << '}'
			g << ''
		}
		g << "@[export: 'tx_application_define']"
		g << 'fn tx_application_define(first_unused voidptr) {'
		for thr in threads {
			pr := m.part.thread_prio[thr] or { 10 }
			g << '\tC._tx_thread_create(&g_${thr}_tcb[0], c\'${thr}\', ${thr}_thread_entry, u32(0),'
			g << '\t\t&g_${thr}_stack[0], u32(g_${thr}_stack.len), u32(${pr}), u32(${pr}), u32(0), u32(1))'
			if m.trace.on {
				g << '\tC.trace_bind_thread(&g_${thr}_tcb[0]) // deterministic thread ids, creation order'
			}
		}
		g << '}'
		g << ''
		g << '// boot: the whole image entry — the example\'s main.v is just `gen.boot()`.'
		g << 'pub fn boot() {'
		g << '\tC.duo_wait_clocks() // SysTick assumes the final HCLK: wait out the owner\'s PLL'
		g << '\tC.board_timebase_init()'
		g << '\tC.duo_ioc_init()'
		for sname in wide_writes {
			si := m.sig_of[sname] or { continue }
			g << '\tC.duo_xw_init(u32(${m.duo_xw_off[sname] or { 0 }}), u32(${si.fields.len})) // ${sname}'
		}
		if produces {
			g << '\tC.duo_layout_publish() // AFTER every channel init: the owner may poll now'
		}
		if m.trace.on {
			g << '\tC.trace_arm()'
		}
		g << '\tC._tx_initialize_kernel_enter() // never returns'
		g << '}'

		// ports preamble (same shape as the owner's ports_gen.v)
		mut p := []string{}
		p << '// Code generated by tools/loom2v from ${os.file_name(ecu)} (partition "${part}") — DO NOT EDIT.'
		p << 'module ports'
		p << ''
		p << 'import sig'
		p << sat_ports

		// loom_build.mk: right-size the Scheduler tables to this image's per-thread max.
		mut slots := 1
		for _, regs in sat_regs {
			if regs.len > slots {
				slots = regs.len
			}
		}

		for sub in ['sig', 'ports', 'gen'] {
			os.mkdir_all(os.join_path(img, sub)) or { panic('mkdir ${img}/${sub}: ${err}') }
		}
		write_out(os.join_path(img, 'sig/signals_gen.v'), emit_signals(m.sig_of, m.sig_names,
			ecu))
		write_out(os.join_path(img, 'ports/ports_gen.v'), p)
		write_out(os.join_path(img, 'gen/loom_gen.v'), g)
		write_out(os.join_path(img, 'gen/loom_build.mk'), [
			'# generated by loom2v from the owner\'s ecu.toml — do not edit',
			'LOOM_VDEFS := -d loom_max_tasks=${slots}',
		])
		eprintln('loom2v: satellite image "${part}" -> ${img} (${threads.len} thread(s))')
	}
}

fn write_out(path string, lines []string) {
	os.write_file(path, lines.join('\n') + '\n') or { panic('write ${path}: ${err}') }
}
