// loom2v's DUO codegen — the first slice of multi-image generation: cross-core signals.
//
// One ecu.toml names the signals a SATELLITE core publishes over the shared-SRAM xioc
// channel (boards/common/xioc.h); the generator owns the CONTRACT and the bus-owner's
// half of the wire:
//   - assigns each named signal an xioc slot and emits gen/duo_gen.h — the ONE header
//     both images compile against (the satellite's hand-written app publishes through
//     these defines; slot numbers appear nowhere else),
//   - emits the bus-owning image's reader->CAN wiring: a fresh-gated, period-paced
//     transmit of each frame-bound signal inside the comm loop (via C.duo_poll, the
//     xioc reader living in comm_glue.c),
//   - advertises the signals in the manifest (`# duo signals`).
//
// The satellite IMAGE itself (kernel scaffolding, threads) stays hand-written for now —
// examples/h755_m4_app is the reference the full multi-image emitter will absorb later,
// exactly as threadx_h735 was for the M7 path. Payloads are the xioc cell's {a, b} pair
// (2 x u32, 8-byte frames); typed/wider signals arrive with the full emitter.
//
//   [duo]
//   [[duo.signal]]
//   name      = "m4load"   # -> DUO_SLOT_M4LOAD in gen/duo_gen.h
//   frame     = 0x201      # or a bus.dbc message name; OMIT for a slot with no CAN tx
//   period_ms = 100        # tx cadence (latest value, sent only when fresh)
module main

import toml

const duo_signal_keys = ['name', 'frame', 'period_ms']

struct DuoSignal {
mut:
	name      string
	frame     u32 // 0 = no CAN tx (slot only, e.g. the iocx stress channel)
	period_ms u32 = 100
}

struct DuoCfg {
mut:
	on      bool
	signals []DuoSignal
}

fn parse_duo(doc toml.Doc, dbc string) DuoCfg {
	mut t := DuoCfg{}
	dcfg := doc.value_opt('duo') or { return t }
	dm := dcfg.as_map()
	for k, _ in dm {
		if k != 'signal' {
			panic('loom2v: [duo] unknown key "${k}" — only [[duo.signal]] entries')
		}
	}
	for sv in (dm['signal'] or { toml.Any([]toml.Any{}) }).array() {
		sm := sv.as_map()
		for k, _ in sm {
			if k !in duo_signal_keys {
				panic('loom2v: [[duo.signal]] unknown key "${k}" (allowed: ${duo_signal_keys})')
			}
		}
		mut sig := DuoSignal{}
		sig.name = (sm['name'] or { panic('loom2v: [[duo.signal]] needs name') }).string()
		if sig.name.len == 0 || sig.name.len > 16 {
			panic('loom2v: [[duo.signal]] name "${sig.name}" must be 1..16 chars')
		}
		for ch in sig.name {
			if !((ch >= `a` && ch <= `z`) || (ch >= `0` && ch <= `9`) || ch == `_`) {
				panic('loom2v: [[duo.signal]] name "${sig.name}" must be [a-z0-9_] (it becomes a C define)')
			}
		}
		sig.frame = trace_binding(sm, 'frame', 8, 0, dbc)
		sig.period_ms = u32((sm['period_ms'] or { toml.Any(100) }).int())
		for other in t.signals {
			if other.name == sig.name {
				panic('loom2v: [[duo.signal]] duplicate name "${sig.name}"')
			}
		}
		t.signals << sig
	}
	t.on = t.signals.len > 0
	return t
}

// duo_gen_h: the generated cross-core contract header — slots appear ONLY here.
fn duo_gen_h(m Model) []string {
	if !m.duo.on {
		return []string{}
	}
	mut g := []string{}
	g << '/* generated by loom2v from ecu.toml — do not edit. The cross-core signal contract:'
	g << ' * BOTH images compile against these slot assignments (the satellite publishes via'
	g << ' * duo_pub(DUO_SLOT_<NAME>, ...); the bus owner polls the same slots). */'
	g << '#ifndef BLOBLY_DUO_GEN_H'
	g << '#define BLOBLY_DUO_GEN_H'
	for i, sig in m.duo.signals {
		g << '#define DUO_SLOT_${sig.name.to_upper()} ${i}'
	}
	g << '#define DUO_GEN_SLOTS ${m.duo.signals.len}'
	g << '#endif'
	return g
}

fn duo_c_decls(m Model) []string {
	if !m.duo.on {
		return []string{}
	}
	return ['fn C.duo_poll(int, &u32, &u32) int // xioc reader (comm_glue.c): 1 = fresh value']
}

// duo_comm_locals: per-frame-bound-signal pacing state in the comm thread.
fn duo_comm_locals(m Model) []string {
	if !m.duo.on {
		return []string{}
	}
	mut g := []string{}
	for sig in m.duo.signals {
		if sig.frame != 0 {
			g << '\tmut duo_${sig.name}_last := u64(0)'
			g << '\tmut duo_${sig.name}_a := u32(0)'
			g << '\tmut duo_${sig.name}_b := u32(0)'
		}
	}
	if g.len > 0 {
		g.prepend('\t// cross-core signals (gen_duo): last tx time + latest polled value per signal')
		g << '\tmut duo_txf := can.Frame{}'
	}
	return g
}

// duo_produce_drain: poll each slot and transmit frame-bound signals on their period,
// fresh-gated — a stale satellite (or a dead core) simply goes quiet on the bus.
fn duo_produce_drain(m Model) []string {
	if !m.duo.on {
		return []string{}
	}
	mut g := []string{}
	for i, sig in m.duo.signals {
		if sig.frame == 0 {
			continue
		}
		g << '\t\tif C.duo_poll(${i}, &duo_${sig.name}_a, &duo_${sig.name}_b) != 0'
		g << '\t\t\t&& t1 - duo_${sig.name}_last >= ${u64(sig.period_ms) * 1000} && ch.tx_ready() {'
		g << '\t\t\tduo_txf.id = u32(0x${sig.frame.hex()})'
		g << '\t\t\tduo_txf.len = 8'
		g << '\t\t\tduo_txf.data[0] = u8(duo_${sig.name}_a)'
		g << '\t\t\tduo_txf.data[1] = u8(duo_${sig.name}_a >> 8)'
		g << '\t\t\tduo_txf.data[2] = u8(duo_${sig.name}_a >> 16)'
		g << '\t\t\tduo_txf.data[3] = u8(duo_${sig.name}_a >> 24)'
		g << '\t\t\tduo_txf.data[4] = u8(duo_${sig.name}_b)'
		g << '\t\t\tduo_txf.data[5] = u8(duo_${sig.name}_b >> 8)'
		g << '\t\t\tduo_txf.data[6] = u8(duo_${sig.name}_b >> 16)'
		g << '\t\t\tduo_txf.data[7] = u8(duo_${sig.name}_b >> 24)'
		g << '\t\t\tch.send(duo_txf)'
		g << '\t\t\tduo_${sig.name}_last = t1'
		g << '\t\t}'
	}
	return g
}

// duo trace forwarding — the two-core dump. Emitted only when BOTH [duo] and an ISO-TP
// [trace] are on: the rx arm forwards satellite-targeted commands (core-mask bit 1) into
// the dtrace handoff cell, and the comm loop imports the acked snapshot as the remote
// dump block (TraceModule.load_remote → streamed after the local block).
fn duo_trace_on(m Model) bool {
	return m.duo.on && m.trace.on && m.trace.dump_fc_id != 0
}

fn duo_trace_c_decls(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'fn C.duo_trace_req(u32) // post arm(1)/snapshot(2) to the satellite (duo.h dtrace cell)',
		'fn C.duo_trace_ready() int',
		'fn C.duo_trace_count() u32',
		'fn C.duo_trace_buf() &u8',
	]
}

fn duo_trace_globals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return ["\tg_duo_trace_ring [64]trace.Record // the satellite core's imported dump window"]
}

fn duo_trace_locals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\tg_tm.set_remote(u8(1), &g_duo_trace_ring[0], 64) // satellite blocks ride our dump link',
		'\tmut duo_trc_wait := false // a satellite snapshot was requested by op_dump',
	]
}

// the rx-arm extension: parse the SAME trace cmd frame the module gets; bit 1 of the core
// mask (data[6]) addresses the satellite. arm/reset forward as arm; stop forwards as
// freeze+snapshot (so the window is frozen close to the local one); dump waits for the ack.
fn duo_trace_rx_arm(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\t\tif rx.id == u32(0x${m.trace.cmd_id.hex()}) && rx.len == 8 && rx.data[6] & 0x02 != 0 {',
		'\t\t\t\tmatch rx.data[0] {',
		'\t\t\t\t\t1, 2, 4 { C.duo_trace_req(1) } // arm/start/reset -> satellite arm',
		'\t\t\t\t\t3 { C.duo_trace_req(2) } // stop -> satellite freeze+snapshot',
		'\t\t\t\t\t6 { duo_trc_wait = true } // dump -> import the ack below',
		'\t\t\t\t\telse {}',
		'\t\t\t\t}',
		'\t\t\t}',
	]
}

fn duo_trace_poll(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\tif duo_trc_wait && C.duo_trace_ready() != 0 {',
		'\t\t\tg_tm.load_remote(C.duo_trace_buf(), C.duo_trace_count())',
		'\t\t\tduo_trc_wait = false',
		'\t\t}',
	]
}

fn duo_manifest(m Model) []string {
	if !m.duo.on {
		return []string{}
	}
	mut g := ['# duo signals: name,slot,frame']
	for i, sig in m.duo.signals {
		fr := if sig.frame != 0 { '0x${sig.frame.hex()}' } else { '-' }
		g << '${sig.name},${i},${fr}'
	}
	return g
}
