// loom2v's cross-core signal emission — the xioc half of multi-image generation.
//
// There is NO config here: a signal whose `from` partition lives in another image is
// REMOTE (derived in build_model, docs/multi-image.md), and every remote signal gets an
// xioc slot (boards/common/xioc.h) in declaration order. This file owns:
//   - gen/duo_gen.h — the ONE contract header both images compile against (the satellite
//     publishes via duo_pub(DUO_SLOT_<NAME>, ...); the bus owner polls the same slots;
//     slot numbers appear nowhere else),
//   - the bus-owning image's reader->CAN wiring: a fresh-gated, period-paced transmit of
//     each frame-bound remote signal inside the comm loop (via C.duo_poll, the xioc
//     reader living in comm_glue.c),
//   - the satellite trace forwarding (dtrace handoff cell: arm / freeze+snapshot / import)
//     — gated on satellite PARTITIONS existing, not on signals,
//   - the manifest's `# duo signals` rows.
//
// A remote signal `to = <bus>` is transmitted here; `to = <local partition>` is a slot
// with no generated consumer (platform C — shell m4sig/iocx — reads it via the header).
module main

// duo_on: any cross-image signal slots to wire.
fn duo_on(m Model) bool {
	return m.duo_names.len > 0
}

// has_satellite: any partition whose image lives elsewhere (hand-written or generated) —
// the gate for trace forwarding, which exists per CORE, not per signal.
fn has_satellite(m Model) bool {
	for _, ext in m.part.external {
		if ext {
			return true
		}
	}
	return false
}

// duo_gen_h: the generated cross-core contract header — slots appear ONLY here.
fn duo_gen_h(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	g << '/* generated by loom2v from ecu.toml — do not edit. The cross-core signal contract:'
	g << ' * BOTH images compile against these slot assignments (the satellite publishes via'
	g << ' * duo_pub(DUO_SLOT_<NAME>, ...); the bus owner polls the same slots). */'
	g << '#ifndef BLOBLY_DUO_GEN_H'
	g << '#define BLOBLY_DUO_GEN_H'
	mut pairs := 0
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		if si.wide {
			continue
		}
		g << '#define DUO_SLOT_${snake(sname).to_upper()} ${m.duo_idx[sname] or { 0 }}'
		pairs++
	}
	g << '#define DUO_GEN_SLOTS ${pairs}'
	g << '/* the layout id: an FNV-1a hash of the WHOLE slot/offset/schema map. The'
	g << ' * satellite acks it against the owner boot nonce (duo.h REQ/ACK cells) after'
	g << ' * init; the owner polls nothing until the ack matches — two images from'
	g << ' * different generator runs never exchange slots. */'
	g << '#define DUO_LAYOUT_ID 0x${duo_layout_id(m).hex()}u'
	if m.duo_xw_total > 0 {
		g << '/* wide (xioc_n) channels: byte offsets inside the board window (duo.h DUO_XW_ADDR);'
		g << ' * words = u32 lanes, one per field. The satellite inits + writes, the owner polls. */'
		for sname in m.duo_names {
			si := m.sig_of[sname] or { continue }
			if !si.wide {
				continue
			}
			u := snake(sname).to_upper()
			g << '#define DUO_XW_${u}_OFF ${m.duo_xw_off[sname] or { 0 }}u'
			g << '#define DUO_XW_${u}_WORDS ${si.fields.len}u'
		}
		g << '#define DUO_XW_TOTAL ${m.duo_xw_total}u'
		g << '#if defined(DUO_XW_MAX) && (DUO_XW_TOTAL > DUO_XW_MAX)'
		g << '#error "wide xioc channels overflow the board window — grow DUO_XW_MAX (duo.h) or shed signals"'
		g << '#endif'
	}
	g << '#endif'
	return g
}

// duo_wide_on: any wide (xioc_n) remote signals in the model.
fn duo_wide_on(m Model) bool {
	return m.duo_xw_total > 0
}

// duo_layout_id hashes the complete cross-core map — pair slots, wide offsets, lane
// counts, in declaration order — so ANY layout difference between two generator runs
// (a renumbered slot after a signal changed shape, a moved or resized wide channel)
// yields a different id. FNV-1a over the canonical map string.
fn duo_layout_id(m Model) u32 {
	mut desc := ''
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		// the ORDERED field schema is part of the contract: same name + same lane count
		// with reordered/renamed/retyped fields would otherwise hash identically and a
		// stale image would misinterpret lanes instead of going quiet (codex #211 r6)
		mut fs := ''
		for f in si.fields {
			fs += '${f.name}=${f.typ},'
		}
		if si.wide {
			desc += '${sname}:xw+${m.duo_xw_off[sname] or { 0 }}:${si.fields.len}[${fs}]|'
		} else {
			desc += '${sname}:${m.duo_idx[sname] or { 0 }}[${fs}]|'
		}
	}
	mut h := u32(2166136261)
	for b in desc.bytes() {
		h = (h ^ u32(b)) * 16777619
	}
	if h == 0 {
		// 0 is the RETRACTION sentinel duo_clocks_ready writes: a schema hashing to 0
		// would open polling before the satellite ever published (codex #211 r9)
		h = 0x4C594F31 // 'LYO1'
	}
	return h
}

fn duo_c_decls(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := ['fn C.duo_poll(int, &u32, &u32) int // xioc reader (comm_glue.c): 1 = fresh value']
	g << 'fn C.duo_layout_ok() int // layout-id handshake: 0 = satellite absent or a DIFFERENT build'
	if duo_wide_on(m) {
		g << 'fn C.duo_poll_n(u32, u32, &u32, &u32) int // wide xioc_n reader: (window off, OUR lane count, &rd seq, &lanes[0]) — a mismatched writer reads as never-fresh'
	}
	return g
}

// duo_comm_locals: per-frame-bound-signal pacing state in the comm thread.
fn duo_comm_locals(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		if si.external {
			g << '\tmut duo_${snake(sname)}_last := u64(0)'
			if si.wide {
				// wide reader state: the seq + lane buffer duo_poll_n commits into
				// (last-good retention — on a stale poll the lanes stay untouched)
				g << '\tmut duo_${snake(sname)}_seq := u32(0)'
				g << '\tmut duo_${snake(sname)}_lanes := [${si.fields.len}]u32{}'
			} else {
				g << '\tmut duo_${snake(sname)}_a := u32(0)'
				g << '\tmut duo_${snake(sname)}_b := u32(0)'
			}
		}
	}
	if g.len > 0 {
		g.prepend('\t// cross-core signals (gen_duo): last tx time + latest polled value per signal')
		g << '\tmut duo_txf := can.Frame{}'
	}
	return g
}

// duo_produce_drain: poll each slot and transmit frame-bound signals on their period,
// fresh-gated — a stale satellite (or a dead core) simply goes quiet on the bus.
fn duo_produce_drain(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := []string{}
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		if !si.external {
			continue // slot-only (satellite -> local partition): no CAN tx
		}
		mut cyc := m.frames.tx_cycle_us[si.dbc_msg] or { 0 }
		if cyc <= 0 {
			cyc = 100000 // default cyclic 100 ms if no [[frame]].tx.cycle_ms
		}
		n := snake(sname)
		// ORDER MATTERS, twice over: the poll consumes the slot's freshness, so
		// every OTHER gate must fail first. NM sleep (emb#135) and now pacing +
		// tx_ready too (codex #211 r3) — polling first ate a fresh value that
		// arrived off-cycle or under backpressure, and with no later publish it
		// never transmitted. Short-circuit keeps it unconsumed until eligible.
		if si.wide {
			// wide (xioc_n): the poll commits the lanes as a unit; the lean encode packs
			// each u32 lane LE at byte 4*lane — same contract the pair path had, generalized
			// (DLC == 4 * lanes is validated in the comm-thread walk; > 8 needs FD and the
			// classic comm thread rejects it there, loudly).
			off := m.duo_xw_off[sname] or { 0 }
			g << '\t\tif ${nm_gate(m)}C.duo_layout_ok() != 0 && t1 - duo_${n}_last >= u64(${cyc}) && ch.tx_ready()'
			g << '\t\t\t&& C.duo_poll_n(u32(${off}), ${si.fields.len}, &duo_${n}_seq, &duo_${n}_lanes[0]) != 0 {' // REQ-COM-007
			g << '\t\t\tduo_txf.id = u32(0x${si.dbc_id.hex()})'
			g << '\t\t\tduo_txf.len = ${si.dbc_dlc}'
			for j in 0 .. si.fields.len {
				g << '\t\t\tduo_txf.data[${j * 4}] = u8(duo_${n}_lanes[${j}])'
				g << '\t\t\tduo_txf.data[${j * 4 + 1}] = u8(duo_${n}_lanes[${j}] >> 8)'
				g << '\t\t\tduo_txf.data[${j * 4 + 2}] = u8(duo_${n}_lanes[${j}] >> 16)'
				g << '\t\t\tduo_txf.data[${j * 4 + 3}] = u8(duo_${n}_lanes[${j}] >> 24)'
			}
			g << '\t\t\tch.send(duo_txf)'
			g << '\t\t\tduo_${n}_last = t1'
			g << '\t\t}'
			continue
		}
		slot := m.duo_idx[sname] or { 0 }
		g << '\t\tif ${nm_gate(m)}C.duo_layout_ok() != 0 && t1 - duo_${n}_last >= u64(${cyc}) && ch.tx_ready()'
		g << '\t\t\t&& C.duo_poll(${slot}, &duo_${n}_a, &duo_${n}_b) != 0 {' // REQ-COM-007
		g << '\t\t\tduo_txf.id = u32(0x${si.dbc_id.hex()})'
		g << '\t\t\tduo_txf.len = ${si.dbc_dlc}'
		g << '\t\t\tduo_txf.data[0] = u8(duo_${n}_a)'
		g << '\t\t\tduo_txf.data[1] = u8(duo_${n}_a >> 8)'
		g << '\t\t\tduo_txf.data[2] = u8(duo_${n}_a >> 16)'
		g << '\t\t\tduo_txf.data[3] = u8(duo_${n}_a >> 24)'
		if si.dbc_dlc == 8 {
			g << '\t\t\tduo_txf.data[4] = u8(duo_${n}_b)'
			g << '\t\t\tduo_txf.data[5] = u8(duo_${n}_b >> 8)'
			g << '\t\t\tduo_txf.data[6] = u8(duo_${n}_b >> 16)'
			g << '\t\t\tduo_txf.data[7] = u8(duo_${n}_b >> 24)'
		}
		g << '\t\t\tch.send(duo_txf)'
		g << '\t\t\tduo_${n}_last = t1'
		g << '\t\t}'
	}
	return g
}

// duo trace forwarding — the multi-core dump. Emitted only when a SATELLITE PARTITION and
// an ISO-TP [trace] are both on: the rx arm forwards satellite-targeted commands (core-mask
// bit 1) into the dtrace handoff cell, and the comm loop imports the acked snapshot as the
// remote dump block (TraceModule.load_remote → streamed after the local blocks).
fn duo_trace_on(m Model) bool {
	return has_satellite(m) && m.trace.on && m.trace.dump_fc_id != 0
}

fn duo_trace_c_decls(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'fn C.duo_trace_req(u32) // post arm(1)/snapshot(2) to the satellite (duo.h dtrace cell)',
		'fn C.duo_trace_ready() int',
		'fn C.duo_trace_count() u32',
		'fn C.duo_trace_buf() &u8',
		'fn C.duo_trace_offset(&i32, &u32) int // satellite clock - ours, + its error bound',
	]
}

fn duo_trace_globals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	// +1 slot: load_remote prepends the cross-core offset record to the block, and the import
	// ring is oneshot — sized exactly, a full satellite window would push the LAST record out.
	return ["\tg_duo_trace_ring [${m.trace.buffer_records + 1}]trace.Record // the satellite core's imported dump window (+1 = its offset record)"]
}

fn duo_trace_locals(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\tg_tm.set_remote(u8(1), &g_duo_trace_ring[0], ${m.trace.buffer_records + 1}) // satellite blocks ride our dump link',
		'\tmut duo_trc_wait := false // a satellite snapshot was requested by op_dump',
		'\tmut duo_trc_off := i32(0) // satellite clock - ours, µs (measured by the ack round trip)',
		'\tmut duo_trc_bound := u32(0) // half round-trip: that measurement\'s uncertainty',
	]
}

// the rx-arm extension: parse the SAME trace cmd frame the module gets; bit 1 of the core
// mask (data[6]) addresses the satellite. arm/reset forward as arm; stop forwards as
// freeze+snapshot (so the window is frozen close to the local one); dump waits for the ack.
fn duo_trace_rx_arm(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\t\tif rx.id == u32(0x${m.trace.cmd_id.hex()}) && rx.len == 8 && !rx.ext && rx.data[6] & 0x02 != 0 {',
		'\t\t\t\tmatch rx.data[0] {',
		'\t\t\t\t\t1, 2, 4 { C.duo_trace_req(1) } // arm/start/reset -> satellite arm',
		'\t\t\t\t\t3 { C.duo_trace_req(2) } // stop -> satellite freeze+snapshot',
		'\t\t\t\t\t6 { duo_trc_wait = true } // dump -> import the ack below',
		'\t\t\t\t\telse {}',
		'\t\t\t\t}',
		'\t\t\t}',
	]
}

fn duo_trace_poll(m Model) []string {
	if !duo_trace_on(m) {
		return []string{}
	}
	return [
		'\t\t// latch t3 EVERY tick: duo_trace_ready() stamps t3 on the pass that first sees the',
		'\t\t// ack. Gating it behind duo_trc_wait meant a Stop acked at T got its t3 at the LATER',
		'\t\t// dump press — a 50 ms gap biases the midpoint ~25 ms (codex #186). The call is two',
		'\t\t// volatile reads when idle.',
		'\t\tif C.duo_trace_ready() != 0 && duo_trc_wait {',
		'\t\t\t// The exchange we just completed IS the clock measurement — take it BEFORE',
		'\t\t\t// load_remote, which prepends it to the satellite block so the host can put',
		'\t\t\t// both cores on one timeline (REQ-TRACE-011).',
		'\t\t\t// bound past the u16 wire field (a debugger pause, a >131 ms round trip): OMIT the',
		'\t\t\t// correlation — clamping would understate the error and make a bad alignment look',
		'\t\t\t// trustworthy (codex #186). Unmeasured stays visibly unmeasured.',
		'\t\t\tif C.duo_trace_offset(&duo_trc_off, &duo_trc_bound) != 0 && duo_trc_bound <= 0xffff {',
		'\t\t\t\tg_tm.set_core_offset(duo_trc_off, u16(duo_trc_bound))',
		'\t\t\t} else {',
		'\t\t\t\tg_tm.clear_core_offset() // a REJECTED measurement must not ship the previous dump\'s offset (codex #207)',
		'\t\t\t}',
		'\t\t\tg_tm.load_remote(C.duo_trace_buf(), C.duo_trace_count())',
		'\t\t\tduo_trc_wait = false',
		'\t\t}',
	]
}

fn duo_manifest(m Model) []string {
	if !duo_on(m) {
		return []string{}
	}
	mut g := ['# duo signals: name,slot,frame  (slot: pair index, or xw+<byte offset> for wide)']
	for sname in m.duo_names {
		si := m.sig_of[sname] or { continue }
		fr := if si.external { '0x${si.dbc_id.hex()}' } else { '-' }
		slot := if si.wide {
			'xw+${m.duo_xw_off[sname] or { 0 }}'
		} else {
			(m.duo_idx[sname] or { 0 }).str()
		}
		g << '${sname},${slot},${fr}'
	}
	return g
}
