// scale_gen — emit a LARGE example (bus.dbc + ecu.toml + app FB handlers) for a
// system-load benchmark that runs through the REAL generated stack (bridges,
// codec, Loom, IOC) on real vcans — unlike the synthetic tools/load_bench.
//
// Topology (defaults: 4 partitions, 8 buses, 50 FBs/partition):
//   * buses can0..can{B-1} all on core0; partition pP pinned to core P.
//   * each bus has an Rx message (S signals, decoded -> IOC) and a Tx message
//     (S signals, encoded <- IOC). rx fan out to many FBs -> seqlock transport.
//   * each partition runs FBS FBs in a pipeline over a small internal cell pool;
//     each FB reads ~10 signals (CAN rx + internal) and writes ~10 (internal +
//     some CAN tx + a cross-core hand-off), every 10 ms.
//
//   v run tools/scale_gen/gen.v [partitions] [buses] [fbs_per_partition]
// writes bus.dbc, ecu.toml, app/scale_fbs.v into the current directory.
module main

import os

const sig_per_msg = 8 // signals per CAN message (8x 8-bit = one 8-byte frame)
const pool = 64       // internal cells per partition (shared, single-writer = the core)
const reads_per_fb = 10
const writes_per_fb = 10

fn main() {
	parts := if os.args.len > 1 { os.args[1].int() } else { 4 }
	buses := if os.args.len > 2 { os.args[2].int() } else { 8 }
	fbs := if os.args.len > 3 { os.args[3].int() } else { 50 }

	os.write_file('bus.dbc', gen_dbc(buses)) or { panic(err) }
	os.write_file('ecu.toml', gen_toml(parts, buses, fbs)) or { panic(err) }
	os.write_file('main.v', gen_main(buses)) or { panic(err) }
	os.mkdir_all('app') or {}
	os.write_file('app/scale_fbs.v', gen_fbs(parts, buses, fbs)) or { panic(err) }
	eprintln('scale_gen: ${parts} partitions, ${buses} buses, ${fbs} FBs/part (${parts * fbs} FBs)')
}

// ---- DBC: per bus an Rx and a Tx message, each S 8-bit signals ----
fn gen_dbc(buses int) string {
	mut b := []string{}
	b << 'VERSION ""'
	b << ''
	b << 'BU_: SUT Tester'
	for bus in 0 .. buses {
		b << ''
		b << 'BO_ ${256 + bus} RxMsg_${bus}: 8 Tester'
		for s in 0 .. sig_per_msg {
			b << ' SG_ Rx_${bus}_${s} : ${s * 8}|8@1+ (1,0) [0|255] "" SUT'
		}
		b << 'BO_ ${512 + bus} TxMsg_${bus}: 8 SUT'
		for s in 0 .. sig_per_msg {
			b << ' SG_ Tx_${bus}_${s} : ${s * 8}|8@1+ (1,0) [0|255] "" Tester'
		}
	}
	return b.join('\n') + '\n'
}

// rx signals of partition p are the rx of buses where bus % parts == p
fn rx_buses(p int, parts int, buses int) []int {
	mut out := []int{}
	for bus in 0 .. buses {
		if bus % parts == p {
			out << bus
		}
	}
	return out
}

// reads/writes for FB j in partition p — returns the signal-name lists.
fn fb_reads(p int, j int, parts int, buses int) []string {
	rb := rx_buses(p, parts, buses)
	mut r := []string{}
	// a couple of CAN reads (fan-out rx signals of this partition)
	for k in 0 .. 4 {
		bus := rb[(j + k) % rb.len]
		r << 'Rx_${bus}_${(j + k) % sig_per_msg}'
	}
	// the rest from the internal cell pool (written by earlier FBs)
	for k in 0 .. reads_per_fb - 4 {
		r << 'Int_${p}_${(j * 7 + k) % pool}'
	}
	if j == 0 {
		r << 'Xc_${(p + 1) % parts}' // cross-core hand-off from the next partition
	}
	return r
}

fn fb_writes(p int, j int, parts int, buses int, fbs int) []string {
	rb := rx_buses(p, parts, buses)
	mut w := []string{}
	// most writes go to the internal cell pool (consumed by later FBs)
	for k in 0 .. writes_per_fb - 1 {
		w << 'Int_${p}_${(j * 10 + k) % pool}'
	}
	// one CAN tx for the first few FBs, else another internal write
	tx_slots := rb.len * sig_per_msg
	if j < tx_slots {
		bus := rb[j / sig_per_msg]
		w << 'Tx_${bus}_${j % sig_per_msg}'
	} else if j == fbs - 1 {
		w << 'Xc_${p}' // last FB produces this partition's cross-core signal
	} else {
		w << 'Int_${p}_${(j * 10 + writes_per_fb - 1) % pool}'
	}
	return w
}

fn gen_toml(parts int, buses int, fbs int) string {
	mut b := []string{}
	b << '# GENERATED by tools/scale_gen — a system-load benchmark example.'
	b << '# ${parts} cores, ${buses} CAN buses on core0, ${fbs} FBs/core through the real stack.'
	b << ''
	b << '[import]'
	b << 'dbc = "bus.dbc"'
	b << ''
	// Telemetry: ship each core's processor load as a CpuLoad frame on can0, so a
	// host tool (candump / blobly_net GUI) can watch this 4-core load live.
	b << '[telemetry]'
	b << 'enabled   = true'
	b << 'bus       = "can0"'
	b << 'id        = 0x7E0'
	b << 'period_ms = 500'
	b << ''
	for bus in 0 .. buses {
		b << '[bus.can${bus}]'
		b << 'interface = "vcan${bus}"'
		b << 'fd        = false'
		b << 'core      = 0'
		b << ''
	}
	for p in 0 .. parts {
		b << '[[partition]]'
		b << 'name    = "p${p}"'
		b << 'core    = ${p}'
		b << 'trusted = ${p == 0}'
		b << ''
	}

	// --- signals ---
	// rx: from the bus to the owning partition
	for bus in 0 .. buses {
		for s in 0 .. sig_per_msg {
			b << '[[signal]]'
			b << 'name = "Rx_${bus}_${s}"'
			b << 'fields = { v = "u8" }'
			b << 'from = "can${bus}"'
			b << 'to   = "p${bus % parts}"'
			b << 'transport = "seqlock"'
			b << ''
		}
	}
	// tx: from the owning partition to the bus
	for bus in 0 .. buses {
		for s in 0 .. sig_per_msg {
			b << '[[signal]]'
			b << 'name = "Tx_${bus}_${s}"'
			b << 'fields = { v = "u8" }'
			b << 'from = "p${bus % parts}"'
			b << 'to   = "can${bus}"'
			b << 'transport = "seqlock"'
			b << ''
		}
	}
	// internal cell pool per partition (local FB->FB)
	for p in 0 .. parts {
		for k in 0 .. pool {
			b << '[[signal]]'
			b << 'name = "Int_${p}_${k}"'
			b << 'fields = { v = "u8" }'
			b << 'from = "p${p}"'
			b << 'to   = "p${p}"'
			b << ''
		}
	}
	// cross-core hand-off: partition p -> partition (p-1)
	for p in 0 .. parts {
		b << '[[signal]]'
		b << 'name = "Xc_${p}"'
		b << 'fields = { v = "u8" }'
		b << 'from = "p${p}"'
		b << 'to   = "p${(p + parts - 1) % parts}"'
		b << 'transport = "seqlock"'
		b << ''
	}

	// --- frames: rx deadline + tx mode per message ---
	for bus in 0 .. buses {
		b << '[[frame]]'
		b << 'name = "RxMsg_${bus}"'
		b << 'bus  = "can${bus}"'
		b << 'rx   = { timeout_ms = 200 }'
		b << ''
		b << '[[frame]]'
		b << 'name = "TxMsg_${bus}"'
		b << 'bus  = "can${bus}"'
		b << 'tx   = { mode = "cyclic", cycle_ms = 10 }'
		b << ''
	}

	// --- FBs ---
	for p in 0 .. parts {
		for j in 0 .. fbs {
			reads := fb_reads(p, j, parts, buses)
			writes := fb_writes(p, j, parts, buses, fbs)
			b << '[[fb]]'
			b << 'name      = "Fb_${p}_${j}"'
			b << 'partition = "p${p}"'
			b << '  [[fb.handler]]'
			b << '  name      = "on_10ms"'
			b << '  period_ms = 10'
			b << '  reads     = [${quoted(reads)}]'
			b << '  writes    = [${quoted(writes)}]'
			b << ''
		}
	}
	return b.join('\n') + '\n'
}

fn gen_fbs(parts int, buses int, fbs int) string {
	mut b := []string{}
	b << '// GENERATED by tools/scale_gen — scale-benchmark FB handlers.'
	b << 'module app'
	b << ''
	b << 'import ports'
	for p in 0 .. parts {
		for j in 0 .. fbs {
			reads := fb_reads(p, j, parts, buses)
			writes := fb_writes(p, j, parts, buses, fbs)
			b << ''
			b << 'pub struct Fb_${p}_${j} {'
			b << 'pub mut:'
			b << '\tstate u32'
			b << '}'
			b << ''
			b << 'pub fn (mut fb Fb_${p}_${j}) on_10ms(inp ports.Fb_${p}_${j}In, mut out ports.Fb_${p}_${j}Out) {'
			b << '\tmut acc := fb.state'
			for r in reads {
				b << '\tacc = acc * 1664525 + 1013904223 + u32(inp.${snake(r)}.v)'
			}
			for i, w in writes {
				b << '\tout.${snake(w)}.v = u8(acc >> ${u32(i % 4) * 8})'
			}
			b << '\tfb.state = acc'
			b << '}'
		}
	}
	return b.join('\n') + '\n'
}

// gen_main emits the platform entry: open one vcan per bus, call gen.run with all
// channels (sorted by bus name, matching the generated run() signature).
fn gen_main(buses int) string {
	mut b := []string{}
	b << '// GENERATED by tools/scale_gen — opens ${buses} vcans and runs the partitions.'
	b << 'module main'
	b << ''
	b << 'import driver.can'
	b << 'import gen'
	b << ''
	b << 'fn main() {'
	for bus in 0 .. buses {
		b << '\tmut c${bus} := can.Channel{}'
		b << "\tif !c${bus}.open('vcan${bus}', gen.can${bus}_fd) {"
		b << "\t\teprintln('failed to open vcan${bus} — is vcan up? (make vcan)')"
		b << '\t\treturn'
		b << '\t}'
	}
	mut args := []string{}
	for bus in 0 .. buses {
		args << 'c${bus}'
	}
	b << '\tprintln(\'scale: ${buses} buses, partitions running — measure CPU externally (Ctrl-C to stop)\')'
	b << '\tgen.run(${args.join(', ')})'
	b << '}'
	return b.join('\n') + '\n'
}

fn quoted(xs []string) string {
	mut q := []string{}
	for x in xs {
		q << '"${x}"'
	}
	return q.join(', ')
}

fn snake(name string) string {
	mut out := []u8{}
	for i, c in name {
		is_upper := c >= `A` && c <= `Z`
		if is_upper && i > 0 {
			prev := name[i - 1]
			if (prev >= `a` && prev <= `z`) || (prev >= `0` && prev <= `9`) {
				out << `_`
			}
		}
		if (c >= `a` && c <= `z`) || (c >= `0` && c <= `9`) {
			out << c
		} else if is_upper {
			out << c + 32
		} else {
			out << `_`
		}
	}
	return out.bytestr()
}
