// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct ButtonLampIn {
pub mut:
	// signal "UserButton" — ch, transport triple, io -> app
	user_button sig.UserButton
}
pub struct ButtonLampOut {
pub mut:
	// signal "LedGreen" — ch, transport triple, app -> io
	led_green sig.LedGreen
}
