// Code generated by tools/loom2v from gen-h755.toml — DO NOT EDIT.
module sig

pub struct BtnPressed {
pub mut:
	pressed u32
}

pub struct UserButton {
pub mut:
	pressed bool
}

pub struct LedGreen {
pub mut:
	on bool
}

pub struct LedYellow {
pub mut:
	on bool
}
