// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct DimmerIn {
pub mut:
	// signal "Pot" — ch, transport triple, io -> app
	pot sig.Pot
}
pub struct DimmerOut {
pub mut:
	// signal "FanDuty" — ch, transport triple, app -> io
	fan_duty sig.FanDuty
}
