// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct RemoteLampIn {
pub mut:
	// signal "BtnPressed" — ch, transport double, can0 -> app
	btn_pressed sig.BtnPressed
}
pub struct RemoteLampOut {
pub mut:
	// signal "LedRemote" — ch, transport triple, app -> io
	led_remote sig.LedRemote
}
