// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct SpeedFilterIn {
pub mut:
	// signal "VehicleSpeed" — ch, transport double, can0 -> sense
	vehicle_speed sig.VehicleSpeed
}
pub struct SpeedFilterOut {
pub mut:
	// signal "FilteredSpeed" — local cell in partition "sense"
	filtered_speed sig.FilteredSpeed
}

pub struct OverspeedDetectorIn {
pub mut:
	// signal "FilteredSpeed" — local cell in partition "sense"
	filtered_speed sig.FilteredSpeed
}
pub struct OverspeedDetectorOut {
pub mut:
	// signal "Overspeed" — ch, transport double, sense -> ctrl
	overspeed sig.Overspeed
}

pub struct EngineMonitorIn {
pub mut:
	// signal "EngineSpeed" — ch, transport double, can0 -> ctrl
	engine_speed sig.EngineSpeed
}
pub struct EngineMonitorOut {
pub mut:
	// signal "HighRev" — local cell in partition "ctrl"
	high_rev sig.HighRev
}

pub struct LampControllerIn {
pub mut:
	// signal "Overspeed" — ch, transport double, sense -> ctrl
	overspeed sig.Overspeed
	// signal "HighRev" — local cell in partition "ctrl"
	high_rev sig.HighRev
}
pub struct LampControllerOut {
pub mut:
	// signal "WarnLamp" — ch, transport double, ctrl -> can0
	warn_lamp sig.WarnLamp
	// signal "SecureStatus" — ch, transport double, ctrl -> can0
	secure_status sig.SecureStatus
}
