// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
// Per-FB input/output port structs (signal provenance in comments).
module sig

pub struct SpeedMonitorIn {
pub mut:
	// signal "VehicleSpeed" — ch 0, transport double, io -> app
	vehicle_speed VehicleSpeed
}
pub struct SpeedMonitorOut {
pub mut:
	// signal "WarnLamp" — ch 1, transport double, app -> io
	warn_lamp WarnLamp
}
