// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports


pub struct FastWorkIn {
pub mut:
}
pub struct FastWorkOut {
pub mut:
}

pub struct MedWorkIn {
pub mut:
}
pub struct MedWorkOut {
pub mut:
}

pub struct SlowWorkIn {
pub mut:
}
pub struct SlowWorkOut {
pub mut:
}
