module main

// Bare-metal entry for the generated h735_app. board.c brings up the M7 (550 MHz), the
// DWT timebase, and FDCAN1; then gen.run() — generated by loom2v from ecu.toml — runs
// the single-core Loom superloop (FBs + CpuLoad telemetry). Everything below the board
// glue is generated; this file is just the platform seam.
//
// Entry is main__main() called directly from startup.c (no V _vinit), the bare-metal
// pattern proven by h735_blinky / h735_canecho.

import gen
import driver.can

fn C.board_clock_init()
fn C.board_timebase_init()
fn C.board_can_clock_pins_init()

fn main() {
	C.board_clock_init()          // M7 -> 550 MHz (Direct SMPS + VOS0)
	C.board_timebase_init()       // DWT cycle counter -> board_now_us()
	C.board_can_clock_pins_init() // FDCAN1 kernel clock + PH13/PH14 AF9

	mut ch := can.Channel{}
	if !ch.open('0', false) { // bus index 0 = FDCAN1, classic 500 kbit/s
		for {} // open/init failed (kernel clock?) — halt so a debugger stops here
	}
	gen.run(ch) // generated single-core superloop + CpuLoad tx on this channel
}
