// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct SpeedWorkIn {
pub mut:
	// signal "VehicleSpeed" — ch, transport double, can0 -> app
	vehicle_speed sig.VehicleSpeed
}
pub struct SpeedWorkOut {
pub mut:
}
