// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct GovernorIn {
pub mut:
	// signal "Command" — ch, transport double, can0 -> app
	command sig.Command
}
pub struct GovernorOut {
pub mut:
	// signal "LoadCmd" — local cell in partition "app"
	load_cmd sig.LoadCmd
}

pub struct LoadIn {
pub mut:
	// signal "LoadCmd" — local cell in partition "app"
	load_cmd sig.LoadCmd
}
pub struct LoadOut {
pub mut:
	// signal "Workload" — local cell in partition "app"
	workload sig.Workload
}

pub struct HeartbeatIn {
pub mut:
}
pub struct HeartbeatOut {
pub mut:
}
