// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module sig

pub struct LoadCmd {
pub mut:
	iters u32
}

pub struct Workload {
pub mut:
	v u32
}

pub struct Command {
pub mut:
	code u32
}

pub struct M4Count {
pub mut:
	n u32
	acc u32
}

pub struct M4Stress {
pub mut:
	k u32
	chk u32
}
