// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports

import sig

pub struct SpeedMonitorIn {
pub mut:
	// signal "VehicleSpeed" — ch, transport double, can0 -> mon
	vehicle_speed sig.VehicleSpeed
}
pub struct SpeedMonitorOut {
pub mut:
	// signal "WarnLamp" — ch, transport double, mon -> can1
	warn_lamp sig.WarnLamp
}
