// Code generated by tools/loom2v from ecu.toml — DO NOT EDIT.
module ports


pub struct FastSenseIn {
pub mut:
}
pub struct FastSenseOut {
pub mut:
}

pub struct MedSenseIn {
pub mut:
}
pub struct MedSenseOut {
pub mut:
}

pub struct CtrlWorkIn {
pub mut:
}
pub struct CtrlWorkOut {
pub mut:
}

pub struct SlowCtrlIn {
pub mut:
}
pub struct SlowCtrlOut {
pub mut:
}
