// Code generated by tools/loom2v from gen-h755.toml — DO NOT EDIT.
module ports

import sig

pub struct ButtonLampIn {
pub mut:
	// signal "UserButton" — ch, transport triple, io -> app
	user_button sig.UserButton = sig.UserButton{ pressed: false }
}
pub struct ButtonLampOut {
pub mut:
	// signal "LedGreen" — ch, transport triple, app -> io
	led_green sig.LedGreen
	// signal "BtnPressed" — ch, transport double, app -> can0
	btn_pressed sig.BtnPressed
}

pub struct HeartbeatIn {
pub mut:
}
pub struct HeartbeatOut {
pub mut:
	// signal "LedYellow" — ch, transport triple, app -> io
	led_yellow sig.LedYellow
}
